# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class GlobalJobDispatcherConfiguration(Model):
    """GlobalJobDispatcherConfiguration.

    :param vm_size:
    :type vm_size: list[str]
    :param compute_type: Possible values include: 'AmlCompute'
    :type compute_type: str or
     ~designer.models.GlobalJobDispatcherSupportedComputeType
    """

    _attribute_map = {
        'vm_size': {'key': 'vmSize', 'type': '[str]'},
        'compute_type': {'key': 'computeType', 'type': 'str'},
    }

    def __init__(self, **kwargs):
        super(GlobalJobDispatcherConfiguration, self).__init__(**kwargs)
        self.vm_size = kwargs.get('vm_size', None)
        self.compute_type = kwargs.get('compute_type', None)
