# (C) 2020 Smart Sensor Devices AB

import time

from bleuio_lib.bleuio_funcs import BleuIo

my_dongle = BleuIo()

my_dongle.start_daemon()

runOnce = False


while 1:
    if not runOnce:
        cmd = my_dongle.at_central()
        print(cmd)
        # cmd = my_dongle.at_peripheral()
        # print(cmd)
        # cmd = my_dongle.at()
        # print(cmd)
        # cmd = my_dongle.ate(0)
        # print(cmd)
        # cmd = my_dongle.ati()
        # print(cmd)
        # cmd = my_dongle.ate(1)
        # print(cmd)
        # cmd = my_dongle.at_advdata()
        # print(cmd)
        # cmd = my_dongle.at_advdata("04:09:43:41:54")
        # print(cmd)
        # cmd = my_dongle.at_advstart()
        # print(cmd)
        # time.sleep(2)
        # cmd = my_dongle.at_advstop()
        # print(cmd)
        # cmd = my_dongle.at_advstart("1","500","600","20")
        # print(cmd)
        # time.sleep(2)
        # cmd = my_dongle.at_advstop()
        # print(cmd)
        print(my_dongle.at_findscandata("5B0705"))
        time.sleep(4)
        print(my_dongle.stop_scan())
        find = my_dongle.rx_scanning_results
        print("my_dongle.at_findscandata(5B0705)")
        print("="*21)
        print(find)
        print("="*21)
        # cmd = my_dongle.at_gapconnect("[0]40:48:FD:E5:2C:D9")
        # time.sleep(0.5)
        # print(cmd)
        # cmd = my_dongle.at_gapdisconnect()
        # print(cmd)
        cmd = my_dongle.at_gapscan(10)
        print("my_dongle.at_gapscan(10)")
        print("="*21)
        print(cmd)
        print("="*21)
        print(my_dongle.at_gapscan())
        time.sleep(3)
        print(my_dongle.stop_scan())
        gapscan = my_dongle.rx_scanning_results
        print("my_dongle.at_gapscan()")
        print("="*21)
        print(gapscan)
        print("="*21)
        print(my_dongle.at_gapstatus())
        # cmd = my_dongle.at_gattcread("000b")
        # print(cmd)
        # cmd = my_dongle.at_gattcwrite("000b", "HEJ")
        # print(cmd)
        # cmd = my_dongle.at_gattcwriteb("000b", "010101")
        # print(cmd)
        print(my_dongle.at_scantarget("[1]F3:D1:ED:AD:8A:10"))
        time.sleep(3)
        print(my_dongle.stop_scan())
        scan = my_dongle.rx_scanning_results
        print("my_dongle.at_scantarget([1]F3:D1:ED:AD:8A:10)")
        print("="*21)
        print(scan)
        print("="*21)
        # cmd = my_dongle.at_spssend("hejhej")
        # print(cmd)
        # cmd = my_dongle.at_spssend()
        # print(cmd)
        # my_dongle._send_command("HEJHEJ!")
        # my_dongle.stop_sps()
        time.sleep(0.5)
        help = my_dongle.help()
        print(help)
        runOnce = True
        time.sleep(0.5)
        print("---------------STOP---------------")
