# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guardata/client/gui/forms/bootstrap_organization_widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BootstrapOrganizationWidget(object):
    def setupUi(self, BootstrapOrganizationWidget):
        BootstrapOrganizationWidget.setObjectName("BootstrapOrganizationWidget")
        BootstrapOrganizationWidget.resize(750, 517)
        BootstrapOrganizationWidget.setStyleSheet("#label_device_name, #label_username, #label_password, #label_confirmation, #label_email {\n"
"    color: #999999;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"#scrollArea, #scrollAreaWidgetContents {\n"
"    background-color: #F4F4F4;\n"
"}")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(BootstrapOrganizationWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(20)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_instructions = QtWidgets.QLabel(BootstrapOrganizationWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_instructions.sizePolicy().hasHeightForWidth())
        self.label_instructions.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_instructions.setFont(font)
        self.label_instructions.setText("")
        self.label_instructions.setScaledContents(False)
        self.label_instructions.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_instructions.setWordWrap(True)
        self.label_instructions.setObjectName("label_instructions")
        self.verticalLayout_4.addWidget(self.label_instructions)
        self.scrollArea = QtWidgets.QScrollArea(BootstrapOrganizationWidget)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 750, 453))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_8.setContentsMargins(0, 0, 15, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_username = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_username.setFont(font)
        self.label_username.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_username.setObjectName("label_username")
        self.verticalLayout_5.addWidget(self.label_username)
        self.line_edit_login = QtWidgets.QLineEdit(self.widget_2)
        self.line_edit_login.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit_login.setFont(font)
        self.line_edit_login.setObjectName("line_edit_login")
        self.verticalLayout_5.addWidget(self.line_edit_login)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_email = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_email.setFont(font)
        self.label_email.setObjectName("label_email")
        self.verticalLayout_3.addWidget(self.label_email)
        self.line_edit_email = QtWidgets.QLineEdit(self.widget_2)
        self.line_edit_email.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit_email.setFont(font)
        self.line_edit_email.setObjectName("line_edit_email")
        self.verticalLayout_3.addWidget(self.line_edit_email)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_device_name = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_device_name.setFont(font)
        self.label_device_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_device_name.setObjectName("label_device_name")
        self.verticalLayout_7.addWidget(self.label_device_name)
        self.line_edit_device = QtWidgets.QLineEdit(self.widget_2)
        self.line_edit_device.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit_device.setFont(font)
        self.line_edit_device.setPlaceholderText("")
        self.line_edit_device.setObjectName("line_edit_device")
        self.verticalLayout_7.addWidget(self.line_edit_device)
        self.verticalLayout.addLayout(self.verticalLayout_7)
        self.widget_password = QtWidgets.QWidget(self.widget_2)
        self.widget_password.setObjectName("widget_password")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_password)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_password = QtWidgets.QLabel(self.widget_password)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_password.setFont(font)
        self.label_password.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_password.setObjectName("label_password")
        self.verticalLayout_10.addWidget(self.label_password)
        self.line_edit_password = QtWidgets.QLineEdit(self.widget_password)
        self.line_edit_password.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit_password.setFont(font)
        self.line_edit_password.setText("")
        self.line_edit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_password.setPlaceholderText("")
        self.line_edit_password.setObjectName("line_edit_password")
        self.verticalLayout_10.addWidget(self.line_edit_password)
        self.verticalLayout_2.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_confirmation = QtWidgets.QLabel(self.widget_password)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_confirmation.setFont(font)
        self.label_confirmation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_confirmation.setObjectName("label_confirmation")
        self.verticalLayout_11.addWidget(self.label_confirmation)
        self.line_edit_password_check = QtWidgets.QLineEdit(self.widget_password)
        self.line_edit_password_check.setMinimumSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit_password_check.setFont(font)
        self.line_edit_password_check.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_password_check.setPlaceholderText("")
        self.line_edit_password_check.setObjectName("line_edit_password_check")
        self.verticalLayout_11.addWidget(self.line_edit_password_check)
        self.verticalLayout_2.addLayout(self.verticalLayout_11)
        self.layout_password_strength = QtWidgets.QHBoxLayout()
        self.layout_password_strength.setObjectName("layout_password_strength")
        self.verticalLayout_2.addLayout(self.layout_password_strength)
        self.verticalLayout.addWidget(self.widget_password)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setSpacing(4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_bootstrap = QtWidgets.QPushButton(self.widget_2)
        self.button_bootstrap.setMaximumSize(QtCore.QSize(250, 16777215))
        self.button_bootstrap.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_bootstrap.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.button_bootstrap.setIconSize(QtCore.QSize(20, 20))
        self.button_bootstrap.setFlat(False)
        self.button_bootstrap.setObjectName("button_bootstrap")
        self.horizontalLayout_3.addWidget(self.button_bootstrap)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_8.addWidget(self.widget_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)

        self.retranslateUi(BootstrapOrganizationWidget)
        QtCore.QMetaObject.connectSlotsByName(BootstrapOrganizationWidget)

    def retranslateUi(self, BootstrapOrganizationWidget):
        _translate = QtCore.QCoreApplication.translate
        BootstrapOrganizationWidget.setWindowTitle(_translate("BootstrapOrganizationWidget", "Form"))
        self.label_username.setText(_translate("BootstrapOrganizationWidget", "TEXT_LABEL_USER_FULL_NAME"))
        self.line_edit_login.setPlaceholderText(_translate("BootstrapOrganizationWidget", "TEXT_LABEL_USER_FULL_NAME_PLACEHOLDER"))
        self.label_email.setText(_translate("BootstrapOrganizationWidget", "TEXT_LABEL_USER_EMAIL"))
        self.line_edit_email.setPlaceholderText(_translate("BootstrapOrganizationWidget", "TEXT_LABEL_USER_EMAIL_PLACEHOLDER"))
        self.label_device_name.setText(_translate("BootstrapOrganizationWidget", "TEXT_LABEL_DEVICE_NAME"))
        self.label_password.setText(_translate("BootstrapOrganizationWidget", "TEXT_LABEL_PASSWORD"))
        self.label_confirmation.setText(_translate("BootstrapOrganizationWidget", "TEXT_LABEL_PASSWORD_CONFIRMATION"))
        self.button_bootstrap.setToolTip(_translate("BootstrapOrganizationWidget", "TEXT_BOOTSTRAP_ORG_TOOLTIP"))
        self.button_bootstrap.setText(_translate("BootstrapOrganizationWidget", "ACTION_BOOTSTRAP_ORG"))
