# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guardata/client/gui/forms/claim_user_finalize_widget.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ClaimUserFinalizeWidget(object):
    def setupUi(self, ClaimUserFinalizeWidget):
        ClaimUserFinalizeWidget.setObjectName("ClaimUserFinalizeWidget")
        ClaimUserFinalizeWidget.resize(400, 240)
        self.verticalLayout = QtWidgets.QVBoxLayout(ClaimUserFinalizeWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(ClaimUserFinalizeWidget)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.widget_password = QtWidgets.QWidget(ClaimUserFinalizeWidget)
        self.widget_password.setObjectName("widget_password")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_password)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_password = QtWidgets.QLabel(self.widget_password)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_password.setFont(font)
        self.label_password.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_password.setObjectName("label_password")
        self.verticalLayout_8.addWidget(self.label_password)
        self.line_edit_password = QtWidgets.QLineEdit(self.widget_password)
        self.line_edit_password.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit_password.setFont(font)
        self.line_edit_password.setText("")
        self.line_edit_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_password.setObjectName("line_edit_password")
        self.verticalLayout_8.addWidget(self.line_edit_password)
        self.verticalLayout_2.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_confirmation = QtWidgets.QLabel(self.widget_password)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_confirmation.setFont(font)
        self.label_confirmation.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_confirmation.setObjectName("label_confirmation")
        self.verticalLayout_9.addWidget(self.label_confirmation)
        self.line_edit_password_check = QtWidgets.QLineEdit(self.widget_password)
        self.line_edit_password_check.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_edit_password_check.setFont(font)
        self.line_edit_password_check.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line_edit_password_check.setObjectName("line_edit_password_check")
        self.verticalLayout_9.addWidget(self.line_edit_password_check)
        self.verticalLayout_2.addLayout(self.verticalLayout_9)
        self.layout_password_strength = QtWidgets.QHBoxLayout()
        self.layout_password_strength.setObjectName("layout_password_strength")
        self.password_strength_widget = PasswordStrengthWidget(self.widget_password)
        self.password_strength_widget.setObjectName("password_strength_widget")
        self.layout_password_strength.addWidget(self.password_strength_widget)
        self.verticalLayout_2.addLayout(self.layout_password_strength)
        self.verticalLayout.addWidget(self.widget_password)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.button_finalize = QtWidgets.QPushButton(ClaimUserFinalizeWidget)
        self.button_finalize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_finalize.setObjectName("button_finalize")
        self.horizontalLayout.addWidget(self.button_finalize)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ClaimUserFinalizeWidget)
        QtCore.QMetaObject.connectSlotsByName(ClaimUserFinalizeWidget)

    def retranslateUi(self, ClaimUserFinalizeWidget):
        _translate = QtCore.QCoreApplication.translate
        ClaimUserFinalizeWidget.setWindowTitle(_translate("ClaimUserFinalizeWidget", "Form"))
        self.label.setText(_translate("ClaimUserFinalizeWidget", "TEXT_CLAIM_USER_FINALIZE_INSTRUCTIONS"))
        self.label_password.setText(_translate("ClaimUserFinalizeWidget", "TEXT_LABEL_PASSWORD"))
        self.line_edit_password.setPlaceholderText(_translate("ClaimUserFinalizeWidget", "TEXT_LABEL_PASSWORD_PLACEHOLDER"))
        self.label_confirmation.setText(_translate("ClaimUserFinalizeWidget", "TEXT_LABEL_PASSWORD_CONFIRMATION"))
        self.line_edit_password_check.setPlaceholderText(_translate("ClaimUserFinalizeWidget", "TEXT_LABEL_PASSWORD_CONFIRMATION_PLACEHOLDER"))
        self.button_finalize.setText(_translate("ClaimUserFinalizeWidget", "ACTION_OK"))
from guardata.client.gui.password_validation import PasswordStrengthWidget
