
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-18T09:41:22-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "17925818edf200755783cc636d87f62e6311ff4f",
 "version": "4.3.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
