# coding: utf-8

"""
    IIMMPACT API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2020-09-14T13:01:14Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import iimmpact
from iimmpact.api.transaction_history_api import TransactionHistoryApi  # noqa: E501
from iimmpact.rest import ApiException


class TestTransactionHistoryApi(unittest.TestCase):
    """TransactionHistoryApi unit test stubs"""

    def setUp(self):
        self.api = iimmpact.api.transaction_history_api.TransactionHistoryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_balance_statement_get(self):
        """Test case for v1_balance_statement_get

        """
        pass

    def test_v1_transactions_get(self):
        """Test case for v1_transactions_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
