# coding: utf-8

"""
    IIMMPACT API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2020-09-14T13:01:14Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import iimmpact
from iimmpact.models.low_balance_warning_response_metadata import LowBalanceWarningResponseMetadata  # noqa: E501
from iimmpact.rest import ApiException


class TestLowBalanceWarningResponseMetadata(unittest.TestCase):
    """LowBalanceWarningResponseMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLowBalanceWarningResponseMetadata(self):
        """Test LowBalanceWarningResponseMetadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = iimmpact.models.low_balance_warning_response_metadata.LowBalanceWarningResponseMetadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
