# coding: utf-8

"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "algorithmia-api-client"
VERSION = "1.3.1"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Algorithmia Management APIs",
    author="Algorithmia Support Team",
    author_email="support@algorithmia.com",
    license="Apache License 2.0",
    classifiers=[
        'License :: OSI Approved :: Apache Software License',
    ],
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Algorithmia Management APIs"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="""\
    APIs for managing actions on the Algorithmia platform  # noqa: E501
    """
)
