# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/builds/clients/python/sakia/src/sakia/gui/preferences.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName("PreferencesDialog")
        PreferencesDialog.resize(711, 326)
        self.verticalLayout = QtWidgets.QVBoxLayout(PreferencesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(6, -1, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.button_app = QtWidgets.QPushButton(PreferencesDialog)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/settings_app_icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_app.setIcon(icon)
        self.button_app.setIconSize(QtCore.QSize(65, 65))
        self.button_app.setFlat(False)
        self.button_app.setObjectName("button_app")
        self.verticalLayout_6.addWidget(self.button_app)
        self.button_display = QtWidgets.QPushButton(PreferencesDialog)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/settings_display_icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_display.setIcon(icon1)
        self.button_display.setIconSize(QtCore.QSize(65, 65))
        self.button_display.setFlat(False)
        self.button_display.setObjectName("button_display")
        self.verticalLayout_6.addWidget(self.button_display)
        self.button_network = QtWidgets.QPushButton(PreferencesDialog)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/settings_network_icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_network.setIcon(icon2)
        self.button_network.setIconSize(QtCore.QSize(65, 65))
        self.button_network.setFlat(False)
        self.button_network.setObjectName("button_network")
        self.verticalLayout_6.addWidget(self.button_network)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.line = QtWidgets.QFrame(PreferencesDialog)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.stackedWidget = QtWidgets.QStackedWidget(PreferencesDialog)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_7 = QtWidgets.QLabel(self.page)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.combo_referential = QtWidgets.QComboBox(self.page)
        self.combo_referential.setObjectName("combo_referential")
        self.horizontalLayout_3.addWidget(self.combo_referential)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.line_2 = QtWidgets.QFrame(self.page)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_7.addWidget(self.line_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.checkbox_expertmode = QtWidgets.QCheckBox(self.page)
        self.checkbox_expertmode.setObjectName("checkbox_expertmode")
        self.horizontalLayout_4.addWidget(self.checkbox_expertmode)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.spinbox_digits_comma = QtWidgets.QSpinBox(self.page_2)
        self.spinbox_digits_comma.setObjectName("spinbox_digits_comma")
        self.horizontalLayout_6.addWidget(self.spinbox_digits_comma)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.combo_language = QtWidgets.QComboBox(self.page_2)
        self.combo_language.setObjectName("combo_language")
        self.horizontalLayout_7.addWidget(self.combo_language)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.line_3 = QtWidgets.QFrame(self.page_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.checkbox_maximize = QtWidgets.QCheckBox(self.page_2)
        self.checkbox_maximize.setObjectName("checkbox_maximize")
        self.horizontalLayout_5.addWidget(self.checkbox_maximize)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.checkbox_notifications = QtWidgets.QCheckBox(self.page_2)
        self.checkbox_notifications.setObjectName("checkbox_notifications")
        self.horizontalLayout_8.addWidget(self.checkbox_notifications)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.checkbox_dark_theme = QtWidgets.QCheckBox(self.page_2)
        self.checkbox_dark_theme.setObjectName("checkbox_dark_theme")
        self.horizontalLayout_11.addWidget(self.checkbox_dark_theme)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.page_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.checkbox_proxy = QtWidgets.QCheckBox(self.page_3)
        self.checkbox_proxy.setObjectName("checkbox_proxy")
        self.verticalLayout_3.addWidget(self.checkbox_proxy)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.page_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.edit_proxy_address = QtWidgets.QLineEdit(self.page_3)
        self.edit_proxy_address.setObjectName("edit_proxy_address")
        self.horizontalLayout_9.addWidget(self.edit_proxy_address)
        self.label_2 = QtWidgets.QLabel(self.page_3)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.spinbox_proxy_port = QtWidgets.QSpinBox(self.page_3)
        self.spinbox_proxy_port.setObjectName("spinbox_proxy_port")
        self.horizontalLayout_9.addWidget(self.spinbox_proxy_port)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.page_3)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.edit_proxy_username = QtWidgets.QLineEdit(self.page_3)
        self.edit_proxy_username.setObjectName("edit_proxy_username")
        self.horizontalLayout.addWidget(self.edit_proxy_username)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtWidgets.QLabel(self.page_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.edit_proxy_password = QtWidgets.QLineEdit(self.page_3)
        self.edit_proxy_password.setObjectName("edit_proxy_password")
        self.horizontalLayout_10.addWidget(self.edit_proxy_password)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.line_4 = QtWidgets.QFrame(self.page_3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_3.addWidget(self.line_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.stackedWidget.addWidget(self.page_3)
        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(PreferencesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label_3.setBuddy(self.label_3)

        self.retranslateUi(PreferencesDialog)
        self.stackedWidget.setCurrentIndex(2)
        self.buttonBox.accepted.connect(PreferencesDialog.accept)
        self.buttonBox.rejected.connect(PreferencesDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)

    def retranslateUi(self, PreferencesDialog):
        _translate = QtCore.QCoreApplication.translate
        PreferencesDialog.setWindowTitle(_translate("PreferencesDialog", "Preferences"))
        self.button_app.setText(_translate("PreferencesDialog", "General"))
        self.button_display.setText(_translate("PreferencesDialog", "Display"))
        self.button_network.setText(_translate("PreferencesDialog", "Network"))
        self.label_7.setText(_translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">General settings</span></p></body></html>"))
        self.label_3.setText(_translate("PreferencesDialog", "Default &referential"))
        self.checkbox_expertmode.setText(_translate("PreferencesDialog", "Enable expert mode"))
        self.label_9.setText(_translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Display settings</span></p></body></html>"))
        self.label_4.setText(_translate("PreferencesDialog", "Digits after commas "))
        self.label_5.setText(_translate("PreferencesDialog", "Language"))
        self.checkbox_maximize.setText(_translate("PreferencesDialog", "Maximize Window at Startup"))
        self.checkbox_notifications.setText(_translate("PreferencesDialog", "Enable notifications"))
        self.checkbox_dark_theme.setText(_translate("PreferencesDialog", "Dark Theme compatibility"))
        self.label_10.setText(_translate("PreferencesDialog", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600;\">Network settings</span></p></body></html>"))
        self.checkbox_proxy.setText(_translate("PreferencesDialog", "Use a http proxy server"))
        self.label_6.setText(_translate("PreferencesDialog", "Proxy server address"))
        self.label_2.setText(_translate("PreferencesDialog", ":"))
        self.label.setText(_translate("PreferencesDialog", "Proxy username"))
        self.label_8.setText(_translate("PreferencesDialog", "Proxy password"))

import sakia.icons_rc
