
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-13T17:55:34-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "bc2c7b7c81c892fa98a9e96b6f3fb6241c86f13f",
 "version": "v0.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
