# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-18 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_polls', '0006_auto_20200818_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='image',
            field=models.URLField(default='/media/default-image.png', verbose_name="Illustration de l'évènement"),
        ),
    ]
