# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-11 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_polls', '0008_auto_20200820_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='image',
            field=models.URLField(default='http://localhost:8000/media/defaultpoll.png', verbose_name='Illustration'),
        ),
    ]
