# Generated by Django 2.2.16 on 2020-09-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_polls', '0010_auto_20200923_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'control')},
        ),
        migrations.AlterModelOptions(
            name='polloption',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'control')},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'control')},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'control')},
        ),
    ]
