# coding: utf-8

"""
    IIMMPACT API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2020-09-14T13:01:14Z
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class JPJRecordsResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'content_type': 'str',
        'data': 'str',
        'message': 'str'
    }

    attribute_map = {
        'content_type': 'content-type',
        'data': 'data',
        'message': 'message'
    }

    def __init__(self, content_type=None, data=None, message=None):  # noqa: E501
        """JPJRecordsResponse - a model defined in Swagger"""  # noqa: E501

        self._content_type = None
        self._data = None
        self._message = None
        self.discriminator = None

        if content_type is not None:
            self.content_type = content_type
        if data is not None:
            self.data = data
        if message is not None:
            self.message = message

    @property
    def content_type(self):
        """Gets the content_type of this JPJRecordsResponse.  # noqa: E501


        :return: The content_type of this JPJRecordsResponse.  # noqa: E501
        :rtype: str
        """
        return self._content_type

    @content_type.setter
    def content_type(self, content_type):
        """Sets the content_type of this JPJRecordsResponse.


        :param content_type: The content_type of this JPJRecordsResponse.  # noqa: E501
        :type: str
        """

        self._content_type = content_type

    @property
    def data(self):
        """Gets the data of this JPJRecordsResponse.  # noqa: E501


        :return: The data of this JPJRecordsResponse.  # noqa: E501
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this JPJRecordsResponse.


        :param data: The data of this JPJRecordsResponse.  # noqa: E501
        :type: str
        """

        self._data = data

    @property
    def message(self):
        """Gets the message of this JPJRecordsResponse.  # noqa: E501


        :return: The message of this JPJRecordsResponse.  # noqa: E501
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """Sets the message of this JPJRecordsResponse.


        :param message: The message of this JPJRecordsResponse.  # noqa: E501
        :type: str
        """

        self._message = message

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JPJRecordsResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JPJRecordsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
