# Generated by Django 2.2.12 on 2020-05-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0009_programme_intro'),
        ('people', '0014_person_programme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='programme',
        ),
        migrations.AddField(
            model_name='person',
            name='programme',
            field=models.ManyToManyField(blank=True, related_name='persons_programme', to='programmes.Programme'),
        ),
    ]
