#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import pandas as pd
from collections import OrderedDict

dict0_big2b_communion = OrderedDict()
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "affect*"      , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "appreciat*"   , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "approach*"    , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "assist*"      , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "benefit"      , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "care*"        , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "caring*"      , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "chat*"        , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "close*"       , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "commun*"      , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "compassion*"  , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "considerate*" , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "courteous*"   , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "decency"      , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "decent*"      , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "dialogue*"    , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "emotion*"     , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "fair*"        , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "faith*"       , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "friend*"      , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "generous*"    , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "genteel"      , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "gentle*"      , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "gently"       , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "genuine*"     , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "grateful*"    , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "help*"        , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "honest*"      , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "justice"      , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "justly"       , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "kindly"       , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "kindness"     , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "love*"        , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "loving*"      , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "loyal*"       , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "mercy"        , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "modest*"      , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "moral*"       , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "open*"        , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "patiently"    , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "polite*"      , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "praise"       , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "protect*"     , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "righteous*"   , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "sense"        , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "share"        , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "shared"       , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "shares"       , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "sharing"      , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "socia*"       , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "solidarity"   , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "tact*"        , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "talk*"        , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "tender*"      , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "thank*"       , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "together*"    , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "tolerance"    , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "tolerant*"    , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "truth*"       , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "understand*"  , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "union*"       , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "unite*"       , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "unity"        , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "warm*"        , 1 ]
dict0_big2b_communion[len(dict0_big2b_communion)] = [ "yield*"       , 1 ]

df0_big2b_communion = pd.DataFrame.from_dict(
    data    = dict0_big2b_communion,
    orient  = "index",
    columns = ["wildcard","weight",],
)

