
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-15T10:00:46+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "37fcd4b39ea9287f7a486c331918dce164fd3d38",
 "version": "v0.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
