from libs.im_utils.grip_utils import GRIPS as GRIPS
from libs.im_utils.suction_utils import SUCTIONS as SUCTIONS
from typing import Any, Optional

class GRASPS:
    args: Any = ...
    grasp: Any = ...
    types: Any = ...
    disp_colors: Any = ...
    high_score: Any = ...
    def __init__(self, args: Any, grips: Optional[Any] = ..., suctions: Optional[Any] = ..., disp_colors: Optional[Any] = ..., high_score: float = ...) -> None: ...
    len: Any = ...
    best_ind: Any = ...
    def infer(self) -> None: ...
    def get_best_ind(self): ...
    def get_best_grasp(self): ...
    def eval(self, ind: Any): ...
