# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/builds/clients/python/sakia/src/sakia/gui/main_window/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(982, 584)
        MainWindow.setWindowTitle("Sakia")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.top_layout = QtWidgets.QHBoxLayout()
        self.top_layout.setObjectName("top_layout")
        self.verticalLayout_6.addLayout(self.top_layout)
        self.bottom_layout = QtWidgets.QHBoxLayout()
        self.bottom_layout.setObjectName("bottom_layout")
        self.verticalLayout_6.addLayout(self.bottom_layout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionManage_accounts = QtWidgets.QAction(MainWindow)
        self.actionManage_accounts.setObjectName("actionManage_accounts")
        self.actionConfigure_trustable_nodes = QtWidgets.QAction(MainWindow)
        self.actionConfigure_trustable_nodes.setObjectName("actionConfigure_trustable_nodes")
        self.action_add_a_contact = QtWidgets.QAction(MainWindow)
        self.action_add_a_contact.setObjectName("action_add_a_contact")
        self.actionSend_a_message = QtWidgets.QAction(MainWindow)
        self.actionSend_a_message.setObjectName("actionSend_a_message")
        self.actionSend_money = QtWidgets.QAction(MainWindow)
        self.actionSend_money.setObjectName("actionSend_money")
        self.actionRemove_contact = QtWidgets.QAction(MainWindow)
        self.actionRemove_contact.setObjectName("actionRemove_contact")
        self.actionSend_a_message_2 = QtWidgets.QAction(MainWindow)
        self.actionSend_a_message_2.setObjectName("actionSend_a_message_2")
        self.actionSend_money_2 = QtWidgets.QAction(MainWindow)
        self.actionSend_money_2.setObjectName("actionSend_money_2")
        self.actionRemove_contact_2 = QtWidgets.QAction(MainWindow)
        self.actionRemove_contact_2.setObjectName("actionRemove_contact_2")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_quit = QtWidgets.QAction(MainWindow)
        self.action_quit.setObjectName("action_quit")
        self.actionAccount = QtWidgets.QAction(MainWindow)
        self.actionAccount.setObjectName("actionAccount")
        self.actionTransfer_money = QtWidgets.QAction(MainWindow)
        self.actionTransfer_money.setObjectName("actionTransfer_money")
        self.action_configure_parameters = QtWidgets.QAction(MainWindow)
        self.action_configure_parameters.setObjectName("action_configure_parameters")
        self.action_import = QtWidgets.QAction(MainWindow)
        self.action_import.setObjectName("action_import")
        self.action_export = QtWidgets.QAction(MainWindow)
        self.action_export.setObjectName("action_export")
        self.actionCertification = QtWidgets.QAction(MainWindow)
        self.actionCertification.setObjectName("actionCertification")
        self.action_set_as_default = QtWidgets.QAction(MainWindow)
        self.action_set_as_default.setObjectName("action_set_as_default")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.action_add_account = QtWidgets.QAction(MainWindow)
        self.action_add_account.setObjectName("action_add_account")
        self.actionManage_local_node = QtWidgets.QAction(MainWindow)
        self.actionManage_local_node.setObjectName("actionManage_local_node")
        self.action_revoke_identity = QtWidgets.QAction(MainWindow)
        self.action_revoke_identity.setObjectName("action_revoke_identity")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.actionManage_accounts.setText(_translate("MainWindow", "Manage accounts"))
        self.actionConfigure_trustable_nodes.setText(_translate("MainWindow", "Configure trustable nodes"))
        self.action_add_a_contact.setText(_translate("MainWindow", "A&dd a contact"))
        self.actionSend_a_message.setText(_translate("MainWindow", "Send a message"))
        self.actionSend_money.setText(_translate("MainWindow", "Send money"))
        self.actionRemove_contact.setText(_translate("MainWindow", "Remove contact"))
        self.actionSend_a_message_2.setText(_translate("MainWindow", "Send a message"))
        self.actionSend_money_2.setText(_translate("MainWindow", "Send money"))
        self.actionRemove_contact_2.setText(_translate("MainWindow", "Remove contact"))
        self.action_save.setText(_translate("MainWindow", "Save"))
        self.action_quit.setText(_translate("MainWindow", "&Quit"))
        self.actionAccount.setText(_translate("MainWindow", "Account"))
        self.actionTransfer_money.setText(_translate("MainWindow", "&Transfer money"))
        self.action_configure_parameters.setText(_translate("MainWindow", "&Configure"))
        self.action_import.setText(_translate("MainWindow", "&Import"))
        self.action_export.setText(_translate("MainWindow", "&Export"))
        self.actionCertification.setText(_translate("MainWindow", "C&ertification"))
        self.action_set_as_default.setText(_translate("MainWindow", "&Set as default"))
        self.actionAbout.setText(_translate("MainWindow", "A&bout"))
        self.actionPreferences.setText(_translate("MainWindow", "&Preferences"))
        self.action_add_account.setText(_translate("MainWindow", "&Add account"))
        self.actionManage_local_node.setText(_translate("MainWindow", "&Manage local node"))
        self.action_revoke_identity.setText(_translate("MainWindow", "&Revoke an identity"))

import sakia.icons_rc
