
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-09-17T16:37:25-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "60d34f4f2e617a0b24a043e755085a1102b5e73b",
 "version": "1.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
