# coding: utf-8

"""
    Dkube api server

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 0.2.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class InlineResponse20027Data(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'run': 'JobModel',
        'outputs': 'list[InlineResponse20027DataOutputs]'
    }

    attribute_map = {
        'run': 'run',
        'outputs': 'outputs'
    }

    def __init__(self, run=None, outputs=None):  # noqa: E501
        """InlineResponse20027Data - a model defined in Swagger"""  # noqa: E501

        self._run = None
        self._outputs = None
        self.discriminator = None

        if run is not None:
            self.run = run
        if outputs is not None:
            self.outputs = outputs

    @property
    def run(self):
        """Gets the run of this InlineResponse20027Data.  # noqa: E501


        :return: The run of this InlineResponse20027Data.  # noqa: E501
        :rtype: JobModel
        """
        return self._run

    @run.setter
    def run(self, run):
        """Sets the run of this InlineResponse20027Data.


        :param run: The run of this InlineResponse20027Data.  # noqa: E501
        :type: JobModel
        """

        self._run = run

    @property
    def outputs(self):
        """Gets the outputs of this InlineResponse20027Data.  # noqa: E501


        :return: The outputs of this InlineResponse20027Data.  # noqa: E501
        :rtype: list[InlineResponse20027DataOutputs]
        """
        return self._outputs

    @outputs.setter
    def outputs(self, outputs):
        """Sets the outputs of this InlineResponse20027Data.


        :param outputs: The outputs of this InlineResponse20027Data.  # noqa: E501
        :type: list[InlineResponse20027DataOutputs]
        """

        self._outputs = outputs

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20027Data, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20027Data):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
