from ttcv.import_basic_utils import *
from ..dataset.dataset import Dataset as Dataset
from ..processing.grasp_proposing import EdgePairFinder as EdgePairFinder
from ..processing.grip_scoring import GripScorer as GripScorer
from ..utils.grip_utils import GRIPS as GRIPS
from time import time as time
from ttcv.basic.basic_objects import DetGui
from typing import Any, Optional

class GripDetector(GripScorer, DetGui):
    transform: Any = ...
    def load_params(self, args: Any) -> None: ...
    gidx: Any = ...
    def find_grip_pose_from_edges(self, rgbd: Any): ...
    def find_grip_pose_rgb_depth(self, rgb: Any, depth: Any, bbox: Optional[Any] = ..., ws_pts: Optional[Any] = ..., disp_mode: str = ...): ...
    def show_grips(self, rgbd: Any, Grips: Any, disp_mode: str = ...): ...
    def show_grips_rgb_depth(self, rgb: Any, depth: Any, Grips: Any, bbox: Optional[Any] = ..., ws_pts: Optional[Any] = ..., disp_mode: str = ...): ...
