from KAI.utils.data_processing import *
from KAI.basic.basic_objects import BasObj
from typing import Any, Optional

def show_locs(im: Any, locs: Any, reval_params: Optional[Any] = ..., data_type: Any = ..., color: Any = ...): ...

class GripDetector(BasObj):
    grip_evaluator: Any = ...
    gidx: Any = ...
    def __init__(self, args: Optional[Any] = ..., cfg_path: Optional[Any] = ...) -> None: ...
    def predict_dict(self, inputs: Any, filename: str = ...): ...
