from ttcv.import_basic_utils import *
from time import time as time
from ttcv.basic.basic_objects import BasDetect, DetGuiObj
from typing import Any, Optional

class GripMaskRCNNModel(BasDetect):
    model: Any = ...
    def get_model(self) -> None: ...
    def find_grip_loc(self, in_mask: Any): ...
    def find_grip_pose_candidates(self, masks: Any): ...
    def select_pose(self, grip_poses: Any, fg_mask: Any, grip_plats: Any, depth: Optional[Any] = ...): ...
    def find_grip_pose(self, rgbd: Any, disp_mode: str = ...): ...

class GripMaskRCNNGUiObj(GripMaskRCNNModel, DetGuiObj):
    def get_model(self) -> None: ...
    def gui_process_single(self, rgbd: Any, method_ind: int = ..., filename: str = ..., disp_mode: str = ...): ...
