from libs.utils.proc_utils import *
from libs.detector.maskrcnn_tester import MaskRCNNDetector
from typing import Any

class GripDetector(MaskRCNNDetector):
    def find_grip_loc(self, in_mask: Any, depth_margin: Any, ind: Any): ...
    crop_rect: Any = ...
    def find_grip_pose(self, inputs: Any): ...
