from common.utils.proc_utils import *
from typing import Any, Optional

class GripDetector:
    args: Any = ...
    def __int__(self, args: Any) -> None: ...
    def load_params(self, args: Any) -> None: ...
    def find_grip_loc(self, in_mask: Any, ind: Any, box_org: Any): ...
    def find_grip_pose_candidates(self, org_im: Any, detect_rets: Any): ...
    def select_pose(self, grip_poses: Any, fg_mask: Any, grip_plats: Any, depth: Optional[Any] = ...): ...
    crop_rect: Any = ...
    def find_grip_pose(self, inputs: Any, detect_rets: Any, filename: str = ...): ...
