from ttcv.import_basic_utils import *
from ..dataset.dataset import Dataset as Dataset
from ..utils.suction_utils_v2 import SUCTION as SUCTION, SUCTIONS as SUCTIONS
from ttcv.basic.basic_objects import DetGui as DetGui
from ttdet.cifar_classfication.classification_v2 import BasCifarClassfier
from typing import Any, Optional

def get_suctions_(args: Any, rgbd_crop: Any, edge_crop: Any, array_scales: Any, coor_scales: Any, X: Any, Y: Any, ind_range: Any, org: Any = ...): ...
def get_suctions(args: Any, rgbd_crop: Any, edge_crop: Any, array_scales: Any, coor_scales: Any, X: Any, Y: Any, ind_range: Any, org: Any = ...): ...

class SuctionDetector(BasCifarClassfier):
    def get_suction_candidates(self, rgbd: Any, mask: Optional[Any] = ..., locs: Optional[Any] = ...): ...
    gidx: Any = ...
    def find_suction_pose_multiscale(self, rgbd: Any, mask_det: Optional[Any] = ...): ...
    def find_suction_pose_rgb_depth(self, rgb: Any, depth: Any, bbox: Optional[Any] = ..., ws_pts: Optional[Any] = ..., mask_det: Optional[Any] = ..., disp_mode: str = ...): ...
    def show_suctions(self, rgbd: Any, Suctions: Any, disp_mode: str = ...): ...
    def show_suctions_rgb_depth(self, rgb: Any, depth: Any, Suctions: Any, bbox: Optional[Any] = ..., ws_pts: Optional[Any] = ..., disp_mode: str = ...): ...
