from common.utils.proc_utils import *
from typing import Any

class SuctionDetector:
    args: Any = ...
    def __int__(self, args: Any) -> None: ...
    def load_params(self, args: Any) -> None: ...
    def calc_depth_var_scale(self, depth_crop: Any, scale: Any, nb_radius: Any): ...
    def calc_depth_var(self, depth: Any): ...
    def find_suction_loc(self, prob_map: Any, depth: Any, loc: Any): ...
    def find_valid_suction(self, depth: Any, prob_map: Any, loc1: Any, loc1_erode: Any): ...
    crop_rect: Any = ...
    def find_suction_pose(self, inputs: Any, detect_rets: Any, classes: Any, filename: str = ...): ...
