# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/builds/clients/python/sakia/src/sakia/gui/dialogs/contact/contact.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ContactDialog(object):
    def setupUi(self, ContactDialog):
        ContactDialog.setObjectName("ContactDialog")
        ContactDialog.resize(629, 536)
        self.verticalLayout = QtWidgets.QVBoxLayout(ContactDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(ContactDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.table_contacts = QtWidgets.QTableView(self.groupBox_2)
        self.table_contacts.setObjectName("table_contacts")
        self.table_contacts.horizontalHeader().setStretchLastSection(True)
        self.table_contacts.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.table_contacts)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.button_delete = QtWidgets.QPushButton(self.groupBox_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/not_member"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_delete.setIcon(icon)
        self.button_delete.setObjectName("button_delete")
        self.horizontalLayout_5.addWidget(self.button_delete)
        self.button_clear = QtWidgets.QPushButton(self.groupBox_2)
        self.button_clear.setObjectName("button_clear")
        self.horizontalLayout_5.addWidget(self.button_clear)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 561, 128))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.edit_name = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.edit_name.setObjectName("edit_name")
        self.horizontalLayout.addWidget(self.edit_name)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.edit_pubkey = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.edit_pubkey.setObjectName("edit_pubkey")
        self.horizontalLayout_2.addWidget(self.edit_pubkey)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.add_info_button = QtWidgets.QToolButton(self.scrollAreaWidgetContents)
        self.add_info_button.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.add_info_button.setObjectName("add_info_button")
        self.horizontalLayout_3.addWidget(self.add_info_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.button_save = QtWidgets.QPushButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/add_account_icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_save.setIcon(icon1)
        self.button_save.setIconSize(QtCore.QSize(16, 16))
        self.button_save.setObjectName("button_save")
        self.horizontalLayout_4.addWidget(self.button_save)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.button_box = QtWidgets.QDialogButtonBox(ContactDialog)
        self.button_box.setEnabled(True)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(ContactDialog)
        QtCore.QMetaObject.connectSlotsByName(ContactDialog)

    def retranslateUi(self, ContactDialog):
        _translate = QtCore.QCoreApplication.translate
        ContactDialog.setWindowTitle(_translate("ContactDialog", "Contacts"))
        self.groupBox_2.setTitle(_translate("ContactDialog", "Contacts list"))
        self.button_delete.setText(_translate("ContactDialog", "Delete selected contact"))
        self.button_clear.setText(_translate("ContactDialog", "Clear selection"))
        self.groupBox.setTitle(_translate("ContactDialog", "Contact informations"))
        self.label.setText(_translate("ContactDialog", "Name"))
        self.label_2.setText(_translate("ContactDialog", "Public key"))
        self.add_info_button.setText(_translate("ContactDialog", "Add other informations"))
        self.button_save.setText(_translate("ContactDialog", "Save"))

import sakia.icons_rc
