
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-12T09:52:56+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "0e145ada009a5b1084148de601ab75a34718a8a4",
 "version": "0.1.1.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
