
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-12T15:57:59-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "0f1b9888eb3e8925a732a0d51cf67cbad8148e03",
 "version": "0.0.46"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
