
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-10-21T11:02:45-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "e4b56b40e02f0fa184d365d0985e695f874364e4",
 "version": "1.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
