
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-13T20:19:32-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "e5a6e6a0bf7440b425c55248f156e7f525cc9f32",
 "version": "0.11.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
