# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/builds/clients/python/sakia/src/sakia/gui/sub/transfer/transfer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TransferMoneyWidget(object):
    def setupUi(self, TransferMoneyWidget):
        TransferMoneyWidget.setObjectName("TransferMoneyWidget")
        TransferMoneyWidget.resize(800, 518)
        self.verticalLayout = QtWidgets.QVBoxLayout(TransferMoneyWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_connections = QtWidgets.QWidget(TransferMoneyWidget)
        self.widget_connections.setObjectName("widget_connections")
        self.layout_connections = QtWidgets.QHBoxLayout(self.widget_connections)
        self.layout_connections.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_connections.setObjectName("layout_connections")
        self.label_connections = QtWidgets.QLabel(self.widget_connections)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_connections.setFont(font)
        self.label_connections.setObjectName("label_connections")
        self.layout_connections.addWidget(self.label_connections)
        self.combo_connections = QtWidgets.QComboBox(self.widget_connections)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_connections.sizePolicy().hasHeightForWidth())
        self.combo_connections.setSizePolicy(sizePolicy)
        self.combo_connections.setObjectName("combo_connections")
        self.layout_connections.addWidget(self.combo_connections)
        self.verticalLayout.addWidget(self.widget_connections)
        self.widget_source = QtWidgets.QWidget(TransferMoneyWidget)
        self.widget_source.setObjectName("widget_source")
        self.source_layout = QtWidgets.QHBoxLayout(self.widget_source)
        self.source_layout.setSpacing(6)
        self.source_layout.setObjectName("source_layout")
        self.label_source = QtWidgets.QLabel(self.widget_source)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_source.sizePolicy().hasHeightForWidth())
        self.label_source.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_source.setFont(font)
        self.label_source.setObjectName("label_source")
        self.source_layout.addWidget(self.label_source)
        self.label_source_identifier = QtWidgets.QLabel(self.widget_source)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_source_identifier.sizePolicy().hasHeightForWidth())
        self.label_source_identifier.setSizePolicy(sizePolicy)
        self.label_source_identifier.setObjectName("label_source_identifier")
        self.source_layout.addWidget(self.label_source_identifier)
        self.button_source_check = QtWidgets.QPushButton(self.widget_source)
        self.button_source_check.setEnabled(False)
        self.button_source_check.setObjectName("button_source_check")
        self.source_layout.addWidget(self.button_source_check)
        self.verticalLayout.addWidget(self.widget_source)
        self.group_box_recipient = QtWidgets.QGroupBox(TransferMoneyWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.group_box_recipient.setFont(font)
        self.group_box_recipient.setFlat(False)
        self.group_box_recipient.setObjectName("group_box_recipient")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.group_box_recipient)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radio_pubkey = QtWidgets.QRadioButton(self.group_box_recipient)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_pubkey.sizePolicy().hasHeightForWidth())
        self.radio_pubkey.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.radio_pubkey.setFont(font)
        self.radio_pubkey.setChecked(False)
        self.radio_pubkey.setObjectName("radio_pubkey")
        self.horizontalLayout.addWidget(self.radio_pubkey)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.edit_pubkey = QtWidgets.QLineEdit(self.group_box_recipient)
        self.edit_pubkey.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_pubkey.sizePolicy().hasHeightForWidth())
        self.edit_pubkey.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.edit_pubkey.setFont(font)
        self.edit_pubkey.setInputMask("")
        self.edit_pubkey.setText("")
        self.edit_pubkey.setObjectName("edit_pubkey")
        self.horizontalLayout.addWidget(self.edit_pubkey)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.layout_search_user = QtWidgets.QHBoxLayout()
        self.layout_search_user.setContentsMargins(-1, 6, -1, -1)
        self.layout_search_user.setObjectName("layout_search_user")
        self.radio_search = QtWidgets.QRadioButton(self.group_box_recipient)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_search.sizePolicy().hasHeightForWidth())
        self.radio_search.setSizePolicy(sizePolicy)
        self.radio_search.setObjectName("radio_search")
        self.layout_search_user.addWidget(self.radio_search)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.layout_search_user.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.layout_search_user)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radio_local_key = QtWidgets.QRadioButton(self.group_box_recipient)
        self.radio_local_key.setObjectName("radio_local_key")
        self.horizontalLayout_2.addWidget(self.radio_local_key)
        self.combo_local_keys = QtWidgets.QComboBox(self.group_box_recipient)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.combo_local_keys.setFont(font)
        self.combo_local_keys.setObjectName("combo_local_keys")
        self.horizontalLayout_2.addWidget(self.combo_local_keys)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radio_contacts = QtWidgets.QRadioButton(self.group_box_recipient)
        self.radio_contacts.setObjectName("radio_contacts")
        self.horizontalLayout_6.addWidget(self.radio_contacts)
        self.combo_contacts = QtWidgets.QComboBox(self.group_box_recipient)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.combo_contacts.setFont(font)
        self.combo_contacts.setObjectName("combo_contacts")
        self.horizontalLayout_6.addWidget(self.combo_contacts)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout.addWidget(self.group_box_recipient)
        self.frame = QtWidgets.QFrame(TransferMoneyWidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_total = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_total.setFont(font)
        self.label_total.setObjectName("label_total")
        self.verticalLayout_8.addWidget(self.label_total)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.spinbox_referential = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinbox_referential.setDecimals(6)
        self.spinbox_referential.setMaximum(1e+23)
        self.spinbox_referential.setSingleStep(0.01)
        self.spinbox_referential.setObjectName("spinbox_referential")
        self.horizontalLayout_3.addWidget(self.spinbox_referential)
        self.label_referential_units = QtWidgets.QLabel(self.frame)
        self.label_referential_units.setObjectName("label_referential_units")
        self.horizontalLayout_3.addWidget(self.label_referential_units)
        self.spinbox_amount = QtWidgets.QDoubleSpinBox(self.frame)
        self.spinbox_amount.setWrapping(False)
        self.spinbox_amount.setFrame(True)
        self.spinbox_amount.setReadOnly(False)
        self.spinbox_amount.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.spinbox_amount.setProperty("showGroupSeparator", False)
        self.spinbox_amount.setDecimals(2)
        self.spinbox_amount.setSingleStep(1.0)
        self.spinbox_amount.setProperty("value", 0.0)
        self.spinbox_amount.setObjectName("spinbox_amount")
        self.horizontalLayout_3.addWidget(self.spinbox_amount)
        self.label_amount_units = QtWidgets.QLabel(self.frame)
        self.label_amount_units.setObjectName("label_amount_units")
        self.horizontalLayout_3.addWidget(self.label_amount_units)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_3 = QtWidgets.QGroupBox(TransferMoneyWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.edit_message = QtWidgets.QLineEdit(self.groupBox_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.edit_message.setFont(font)
        self.edit_message.setInputMask("")
        self.edit_message.setText("")
        self.edit_message.setObjectName("edit_message")
        self.verticalLayout_5.addWidget(self.edit_message)
        self.horizontalLayout_7.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(TransferMoneyWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.combo_locks = QtWidgets.QComboBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.combo_locks.setFont(font)
        self.combo_locks.setObjectName("combo_locks")
        self.combo_locks.addItem("")
        self.combo_locks.addItem("")
        self.horizontalLayout_9.addWidget(self.combo_locks)
        self.horizontalLayout_7.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.groupBox = QtWidgets.QGroupBox(TransferMoneyWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.layout_password_input = QtWidgets.QHBoxLayout()
        self.layout_password_input.setObjectName("layout_password_input")
        self.verticalLayout_2.addLayout(self.layout_password_input)
        self.verticalLayout.addWidget(self.groupBox)
        self.button_box = QtWidgets.QDialogButtonBox(TransferMoneyWidget)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)

        self.retranslateUi(TransferMoneyWidget)
        QtCore.QMetaObject.connectSlotsByName(TransferMoneyWidget)

    def retranslateUi(self, TransferMoneyWidget):
        _translate = QtCore.QCoreApplication.translate
        TransferMoneyWidget.setWindowTitle(_translate("TransferMoneyWidget", "Form"))
        self.label_connections.setText(_translate("TransferMoneyWidget", "Select account"))
        self.label_source.setText(_translate("TransferMoneyWidget", "Source"))
        self.label_source_identifier.setText(_translate("TransferMoneyWidget", "Automatic"))
        self.button_source_check.setText(_translate("TransferMoneyWidget", "Check"))
        self.group_box_recipient.setTitle(_translate("TransferMoneyWidget", "Transfer money to"))
        self.radio_pubkey.setText(_translate("TransferMoneyWidget", "&Recipient public key"))
        self.edit_pubkey.setPlaceholderText(_translate("TransferMoneyWidget", "Key"))
        self.radio_search.setText(_translate("TransferMoneyWidget", "Search &user"))
        self.radio_local_key.setText(_translate("TransferMoneyWidget", "Local ke&y"))
        self.radio_contacts.setText(_translate("TransferMoneyWidget", "Con&tact"))
        self.label_total.setText(_translate("TransferMoneyWidget", "Available money: "))
        self.label_3.setText(_translate("TransferMoneyWidget", "Amount"))
        self.label_referential_units.setText(_translate("TransferMoneyWidget", "Units"))
        self.label_amount_units.setText(_translate("TransferMoneyWidget", "Units"))
        self.groupBox_3.setTitle(_translate("TransferMoneyWidget", "Message"))
        self.groupBox_2.setTitle(_translate("TransferMoneyWidget", "Spend condition"))
        self.combo_locks.setItemText(0, _translate("TransferMoneyWidget", "Receiver signature"))
        self.combo_locks.setItemText(1, _translate("TransferMoneyWidget", "Receiver signature or (sender after one week)"))
        self.groupBox.setTitle(_translate("TransferMoneyWidget", "Secret Key / Password"))

