
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-12T15:43:32+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d14e9dc849caf233d606d8db56d69ed1f70ee9f4",
 "version": "1.9.117"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
