
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-11T16:24:57+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2428ae7feb4989ed37092075b8f7fd91b26b6331",
 "version": "0.0.0rc3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
