# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-08-07 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u8fc7\u671f\u65f6\u95f4'),
        ),
        migrations.AddField(
            model_name='task',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u8fc7\u671f\u65f6\u95f4'),
        ),
    ]
