# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-01-08 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20200807_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='is_force',
            field=models.BooleanField(default=False, verbose_name='\u5fc5\u8bfb'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_force',
            field=models.BooleanField(default=False, verbose_name='\u5fc5\u8bfb'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='\u5df2\u53d1\u9001'),
        ),
    ]
