# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-01-14 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20210108_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='target_user_tags',
            field=models.TextField(help_text='\u7b26\u5408\u6807\u7b7e\u7684\u4eba\u624d\u80fd\u6536\u5230\u4fe1\u606f.<p>\u4f8b\u5b50:<p>\u8001\u5e08:\u5f20\u4e09,\u674e\u56db,\u8d75\u4e94<p>\u5b66\u751f:*<p>\u5b66\u751f.\u5e74\u7ea7:\u5927\u4e00,\u5927\u4e8c<p>\u5b66\u751f.\u5165\u5b66\u5c4a\u522b:2019\u5c4a<p>\u5b66\u751f.\u73ed\u7ea7:2018\u7ea7\u6570\u5b57\u5a92\u4f53201801\u73ed,2018\u7ea7\u6570\u5b57\u5a92\u4f53201804\u73ed', verbose_name='\u76ee\u6807\u4eba\u7fa4\u6807\u7b7e'),
        ),
    ]
