#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['yaqd_gage']

package_data = \
{'': ['*']}

install_requires = \
['yaqd-core>=2020.06.3', 'numpy']

extras_require = \
{'dev': ['black', 'pre-commit']}

entry_points = \
{'console_scripts': ['yaqd-gage-compuscope = '
                     'yaqd_gage._compuscope:CompuScope.main']}

setup(name='yaqd-gage',
      version='2021.1.0',
      description='yaq daemons for GaGe hardware',
      author='Blaise Thompson',
      author_email='blaise@untzag.com',
      url='https://yaq.fyi',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      entry_points=entry_points,
      python_requires='>=3.7',
     )
