
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-12T11:00:25-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "e4bacaf0d6d514036af7682a0290d25533f11aab",
 "version": "1.1.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
