# coding: utf-8

"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import algorithmia_api_client
from algorithmia_api_client.models.api_key_creation import ApiKeyCreation  # noqa: E501
from algorithmia_api_client.rest import ApiException

class TestApiKeyCreation(unittest.TestCase):
    """ApiKeyCreation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ApiKeyCreation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = algorithmia_api_client.models.api_key_creation.ApiKeyCreation()  # noqa: E501
        if include_optional :
            return ApiKeyCreation(
                key_label = '0', 
                key_type = 'ManagementKey', 
                permissions = algorithmia_api_client.models.auth_permissions.AuthPermissions(
                    allow_data = True, 
                    allow_data_write = True, 
                    allow_algo = True, 
                    allow_web_algo = True, 
                    referer_host = '0', 
                    allow_algo_management = True, 
                    algo_acl = [
                        '0'
                        ], )
            )
        else :
            return ApiKeyCreation(
                key_type = 'ManagementKey',
        )

    def testApiKeyCreation(self):
        """Test ApiKeyCreation"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
