# coding: utf-8

"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import algorithmia_api_client
from algorithmia_api_client.models.create_request_version_info import CreateRequestVersionInfo  # noqa: E501
from algorithmia_api_client.rest import ApiException

class TestCreateRequestVersionInfo(unittest.TestCase):
    """CreateRequestVersionInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateRequestVersionInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = algorithmia_api_client.models.create_request_version_info.CreateRequestVersionInfo()  # noqa: E501
        if include_optional :
            return CreateRequestVersionInfo(
                sample_input = '0'
            )
        else :
            return CreateRequestVersionInfo(
        )

    def testCreateRequestVersionInfo(self):
        """Test CreateRequestVersionInfo"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
