# coding: utf-8

"""
    Algorithmia Management APIs

    APIs for managing actions on the Algorithmia platform  # noqa: E501

    The version of the OpenAPI document: 1.3.0
    Contact: support@algorithmia.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import algorithmia_api_client
from algorithmia_api_client.models.user import User  # noqa: E501
from algorithmia_api_client.rest import ApiException

class TestUser(unittest.TestCase):
    """User unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test User
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = algorithmia_api_client.models.user.User()  # noqa: E501
        if include_optional :
            return User(
                id = '01234567891011121314151617181920212223242526272829303132333435', 
                fullname = '0', 
                email = 'a', 
                username = 'a', 
                company_name = '0', 
                company_role = '0', 
                self_link = '0', 
                resource_type = '0'
            )
        else :
            return User(
                email = 'a',
                username = 'a',
                resource_type = '0',
        )

    def testUser(self):
        """Test User"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
