
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-13T15:00:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7a4e7e31dc33bdad247ebae864444e5e3873d35b",
 "version": "1.14.4.post.dev46"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
