# autogenerated module
from typing import ClassVar

from ..core import resource as res
from ..models import events_v1 as m_events_v1


class Event(res.NamespacedResourceG, m_events_v1.Event):
    """* **Extends**: ``models.events_v1.Event``
       * **Type**: Namespaced Resource
       * **Accepted client methods**: `delete`, `deletecollection`, `get`, `list` all, `watch` all, `list`, `patch`, `create`, `replace`, `watch`
    """
    _api_info = res.ApiInfo(
        resource=res.ResourceDef('events.k8s.io', 'v1', 'Event'),
        plural='events',
        verbs=['delete', 'deletecollection', 'get', 'global_list', 'global_watch', 'list', 'patch', 'post', 'put', 'watch'],
    )

