# autogenerated module
from typing import ClassVar

from ..core import resource as res
from ..models import flowcontrol_v1alpha1 as m_flowcontrol_v1alpha1


class FlowSchemaStatus(res.GlobalSubResource, m_flowcontrol_v1alpha1.FlowSchema):
    """* **Extends**: ``models.flowcontrol_v1alpha1.FlowSchema``
       * **Type**: Global Resource
       * **Accepted client methods**: `get`, `patch`, `replace`
    """
    _api_info = res.ApiInfo(
        resource=res.ResourceDef('flowcontrol.apiserver.k8s.io', 'v1alpha1', 'FlowSchema'),
        parent=res.ResourceDef('flowcontrol.apiserver.k8s.io', 'v1alpha1', 'FlowSchema'),
        plural='flowschemas',
        verbs=['get', 'patch', 'put'],
        action='status',
    )


class FlowSchema(res.GlobalResource, m_flowcontrol_v1alpha1.FlowSchema):
    """* **Extends**: ``models.flowcontrol_v1alpha1.FlowSchema``
       * **Type**: Global Resource
       * **Accepted client methods**: `delete`, `deletecollection`, `get`, `list`, `patch`, `create`, `replace`, `watch`

       **Subresources**:

       * **Status**: ``FlowSchemaStatus``
    """
    _api_info = res.ApiInfo(
        resource=res.ResourceDef('flowcontrol.apiserver.k8s.io', 'v1alpha1', 'FlowSchema'),
        plural='flowschemas',
        verbs=['delete', 'deletecollection', 'get', 'list', 'patch', 'post', 'put', 'watch'],
    )

    Status: ClassVar = FlowSchemaStatus


class PriorityLevelConfigurationStatus(res.GlobalSubResource, m_flowcontrol_v1alpha1.PriorityLevelConfiguration):
    """* **Extends**: ``models.flowcontrol_v1alpha1.PriorityLevelConfiguration``
       * **Type**: Global Resource
       * **Accepted client methods**: `get`, `patch`, `replace`
    """
    _api_info = res.ApiInfo(
        resource=res.ResourceDef('flowcontrol.apiserver.k8s.io', 'v1alpha1', 'PriorityLevelConfiguration'),
        parent=res.ResourceDef('flowcontrol.apiserver.k8s.io', 'v1alpha1', 'PriorityLevelConfiguration'),
        plural='prioritylevelconfigurations',
        verbs=['get', 'patch', 'put'],
        action='status',
    )


class PriorityLevelConfiguration(res.GlobalResource, m_flowcontrol_v1alpha1.PriorityLevelConfiguration):
    """* **Extends**: ``models.flowcontrol_v1alpha1.PriorityLevelConfiguration``
       * **Type**: Global Resource
       * **Accepted client methods**: `delete`, `deletecollection`, `get`, `list`, `patch`, `create`, `replace`, `watch`

       **Subresources**:

       * **Status**: ``PriorityLevelConfigurationStatus``
    """
    _api_info = res.ApiInfo(
        resource=res.ResourceDef('flowcontrol.apiserver.k8s.io', 'v1alpha1', 'PriorityLevelConfiguration'),
        plural='prioritylevelconfigurations',
        verbs=['delete', 'deletecollection', 'get', 'list', 'patch', 'post', 'put', 'watch'],
    )

    Status: ClassVar = PriorityLevelConfigurationStatus

