#!/usr/bin/env python
# coding: utf-8

# In[15]:



Contracted_word={"'aight":" alright ",
    "ain't":" am not ",
    "amn't":" am not ",
    "aren't":" are not ",
    "can't":" cannot ",
    "'cause":" because ",
    "could've":" could have ",
    "couldn't" :" could not ",
    "couldn't've":" could not have ",
    "daren't" :" dare not ",
    "daresn't":" dare not ",
    "dasn't" :" dare not ",
    "didn't" :" did not ",
    "doesn't" :" does not ",
    "don't" :" do not ",
    "dunno" :" do not know ",
    "d'ye" :" do you ",
    "e'er" :" ever ",
    "'em" :" them ",
    "everybody's":" everybody is ",
    "everyone's":" everyone is ",
    "gimme":" give me ",
    "giv'n":" given ",
    "gonna":" going to ",
    "gon't" :" go not ",
    "gotta":" got to ",
    "hadn't":" had not ",
    "had've":" had have ",
    "hasn't":" has not ",
    "haven't" :" have not ",
    "he'd" :" he had ",
    "he'll": " he will ",
    "he's" : " he is ",
    "he've ": " he have ",
    "how'd":" how did ",
    "how'll":" how will ",
    "how're":" how are ",
    "how's":" how is ",
    "I'd" :"I had ",
    "I'd've":" I would have ",
    "I'll" :" I will ",
    "I'm" :" I am ",
    "I'm'a" :" I am about to ",
    "I'm'o" :" I am going to ",
    "I've" :" I have ",
    "isn't" :" is not ",
    "it'd" :" it would ",
    "it'll" :" it will ",
    "it's" :" it is ",
    "kinda":" kind of ",
    "let's":" let us ",
    "ma'am" :" madam ",
    "mayn't":" may not ",
    "may've":" may have ",
    "mightn't" :" might not ",
    "might've" :" might have ",
    "mustn't" :" must not ",
    "mustn't've": " must not have ",
    "must've": " must have ",
    "needn't" :" need not ",
    "oughtn't" :" ought not ",
    "'s":" is ",
    "shalln't" :" shall not ",
    "shan't":" shall not ",
    "she'd":" she had ",
    "she'll":" she will ",
    "she's":" she is ",
    "should've" :" should have ",
    "shouldn't" :" should not ",
    "shouldn't've":" should not have ",
    "somebody's":" somebody is ",
    "someone's" :" someone is ",
    "something's":" something is ",
    "so're":" so are ",
    "that'll" :" that will ",
    "that're":" that are ",
    "that's" :" that is ",
    "that'd":" that had ",
    "there'd":" there had ",
    "there'll" :" there will ",
    "there're" :" there are ",
    "there's" :" there is ",
    "these're" :" these are ",
    "these've" :" these have ",
    "they'd" : " they had ",
    "they'll" :" they will ",
    "they're" :" they are ",
    "they've" :" they have ",
    "this's" :" this is ",
    "wanna":" want to ",
    "wasn't":" was not ",
    "we'd" :" we had ",
    "we'd've":" we would have ",
    "we'll":" we will ",
    "we're": " we are ",
    "we've":" we have ",
    "weren't":" were not ",
    "what'd":" what did ",
    "what'll":" what will ",
    "what're":" what are ",
    "what's" :" what is ",
    "what've" :" what have ",
    "when's":" when is ",
    "where'd": " where did ",
    "where'll" :" where will ",
    "where're" :" where are ",
    "where's" :" where is ",
    "where've" :" where have ",
    "which'd" :" which had ",
    "which'll" :" which will ",
    "which're" :" which are ",
    "which's" :" which is ",
    "which've":" which have ",
    "who'd":" who had ",
    "who'd've" :" who would have ",
    "who'll":" who will ",
    "who're":" who are ",
    "who's":" who is ",
    "who've":" who have ",
    "why'd" :" why did ",
    "why're" :" why are ",
    "why's":" why is ",
    "won't": " will not ",
    "would've" :" would have ",
    "wouldn't" :" would not ",
    "wouldn't've":" would not have ",
    "y'all":" you all ",
    "you'd":" you had ",
    "you'll" :" you will ",
    "you're":" you are ",
    "you've":" you have ",

    }
   
Stop_words=["might","not","can","shall","must","was","is","would",'i',
     'me',
     'my',
     'myself',
     'we',
     'our',
     'ours',
     'ourselves',
     'you',
     "you're",
     "you've",
     "you'll",
     "you'd",
     'your',
     'yours',
     'yourself',
     'yourselves',
     'he',
     'him',
     'his',
     'himself',
     'she',
     "she's",
     'her',
     'hers',
     'herself',
     'it',
     "it's",
     'its',
     'itself',
     'they',
     'them',
     'their',
     'theirs',
     'themselves',
     'what',
     'which',
     'who',
     'whom',
     'this',
     'that',
     "that'll",
     'these',
     'those',
     'am',
     'is',
     'are',
     'was',
     'were',
     'be',
     'been',
     'being',
     'have',
     'has',
     'had',
     'having',
     'do',
     'does',
     'did',
     'doing',
     'a',
     'an',
     'the',
     'and',
     'but',
     'if',
     'or',
     'because',
     'as',
     'until',
     'while',
     'of',
     'at',
     'by',
     'for',
     'with',
     'about',
     'against',
     'between',
     'into',
     'through',
     'during',
     'before',
     'after',
     'above',
     'below',
     'to',
     'from',
     'up',
     'down',
     'in',
     'out',
     'on',
     'off',
     'over',
     'under',
     'again',
     'further',
     'then',
     'once',
     'here',
     'there',
     'when',
     'where',
     'why',
     'how',
     'all',
     'any',
     'both',
     'each',
     'few',
     'more',
     'most',
     'other',
     'some',
     'such',
     'no',
     'nor',
     'not',
     'only',
     'own',
     'same',
     'so',
     'than',
     'too',
     'very',
     's',
     't',
     'can',
     'will',
     'just',
     'don',
     "don't",
     'should',
     "should've",
     'now',
     'd',
     'll',
     'm',
     'o',
     're',
     've',
     'y',
     "are",
     "could",
     "did",
     "does","had",
     'has']

neg_words=["no",
"not",
"none",
"no one",
"nobody",
"nothing",
"neither",
"nowhere",
"never"]
