# Generated by Django 2.2.17 on 2020-12-10 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_project', '0016_remove_project_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djangoldp_invoice', '0003_auto_20201015_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelanceinvoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freelancerInvoices', to='djangoldp_project.Project'),
        ),
        migrations.AddField(
            model_name='freelanceinvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='djangoldp_project.Customer'),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerInvoices', to='djangoldp_project.Project'),
        ),
        migrations.AlterField(
            model_name='customerinvoice',
            name='state',
            field=models.CharField(choices=[('pending', 'en attente'), ('sent', 'envoyé'), ('paid', 'réglée')], default='pending', max_length=255),
        ),
    ]
