# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-20 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_polls', '0007_auto_20200818_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='endDate',
            field=models.DateField(verbose_name='End data'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='image',
            field=models.URLField(default='http://localhost:8000/media/default-image.png', verbose_name='Illustration'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='startDate',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
    ]
