
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-14T15:34:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "eb675cf983efd153124dd090d1bf6dafdca5d73c",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
