
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-12T06:41:05+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a72366afad446a5a070541240aa79cfe82ad952e",
 "version": "0.6.2.post.dev90"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
