# Generated by Django 3.1.4 on 2021-01-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemfromemailaddress',
            name='code_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_for',
            field=models.CharField(max_length=255),
        ),
    ]
