# Generated by Django 3.1.4 on 2021-01-02 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcmailer', '0004_emailtemplate_from_official_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='email_body',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='email_subject',
            new_name='subject',
        ),
    ]
