# Generated by Django 3.1.4 on 2021-01-02 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmailer', '0005_auto_20210102_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='body',
            new_name='html_body',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='plain_body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
