# Generated by Django 3.1.5 on 2021-01-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmailer', '0006_auto_20210102_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='from_official_name',
            new_name='preview_text',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='html_body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='plain_body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='preview_text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='subject_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
