# Generated by Django 3.1.5 on 2021-01-17 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcmailer', '0008_auto_20210118_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='code_name',
            new_name='name',
        ),
    ]
