
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-11T09:45:49-0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "bb4e87c3f5c870f7e5bfcec8bb8a22aca0708e39",
 "version": "0.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
