# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/builds/clients/python/sakia/src/sakia/gui/dialogs/revocation/revocation.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RevocationDialog(object):
    def setupUi(self, RevocationDialog):
        RevocationDialog.setObjectName("RevocationDialog")
        RevocationDialog.resize(452, 358)
        RevocationDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(RevocationDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(RevocationDialog)
        self.stackedWidget.setStyleSheet("QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"    font-weight: bold;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_load_file = QtWidgets.QWidget()
        self.page_load_file.setObjectName("page_load_file")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_load_file)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.page_load_file)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.button_load = QtWidgets.QPushButton(self.page_load_file)
        self.button_load.setObjectName("button_load")
        self.verticalLayout_2.addWidget(self.button_load)
        self.groupBox = QtWidgets.QGroupBox(self.page_load_file)
        self.groupBox.setStyleSheet("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_revocation_content = QtWidgets.QLabel(self.groupBox)
        self.label_revocation_content.setText("")
        self.label_revocation_content.setObjectName("label_revocation_content")
        self.verticalLayout_3.addWidget(self.label_revocation_content)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.stackedWidget.addWidget(self.page_load_file)
        self.page_destination = QtWidgets.QWidget()
        self.page_destination.setObjectName("page_destination")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_destination)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.page_destination)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radio_currency = QtWidgets.QRadioButton(self.page_destination)
        self.radio_currency.setObjectName("radio_currency")
        self.horizontalLayout_2.addWidget(self.radio_currency)
        self.combo_currency = QtWidgets.QComboBox(self.page_destination)
        self.combo_currency.setObjectName("combo_currency")
        self.horizontalLayout_2.addWidget(self.combo_currency)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radio_address = QtWidgets.QRadioButton(self.page_destination)
        self.radio_address.setObjectName("radio_address")
        self.horizontalLayout_3.addWidget(self.radio_address)
        self.edit_address = QtWidgets.QLineEdit(self.page_destination)
        self.edit_address.setObjectName("edit_address")
        self.horizontalLayout_3.addWidget(self.edit_address)
        self.spinbox_port = QtWidgets.QSpinBox(self.page_destination)
        self.spinbox_port.setMaximum(65535)
        self.spinbox_port.setProperty("value", 8201)
        self.spinbox_port.setObjectName("spinbox_port")
        self.horizontalLayout_3.addWidget(self.spinbox_port)
        self.checkbox_secured = QtWidgets.QCheckBox(self.page_destination)
        self.checkbox_secured.setObjectName("checkbox_secured")
        self.horizontalLayout_3.addWidget(self.checkbox_secured)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_destination)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_revocation_info = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_revocation_info.sizePolicy().hasHeightForWidth())
        self.label_revocation_info.setSizePolicy(sizePolicy)
        self.label_revocation_info.setText("")
        self.label_revocation_info.setObjectName("label_revocation_info")
        self.verticalLayout_5.addWidget(self.label_revocation_info)
        self.label_target = QtWidgets.QLabel(self.groupBox_2)
        self.label_target.setText("")
        self.label_target.setObjectName("label_target")
        self.verticalLayout_5.addWidget(self.label_target)
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.stackedWidget.addWidget(self.page_destination)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.button_next = QtWidgets.QPushButton(RevocationDialog)
        self.button_next.setObjectName("button_next")
        self.horizontalLayout.addWidget(self.button_next)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(RevocationDialog)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(RevocationDialog)

    def retranslateUi(self, RevocationDialog):
        _translate = QtCore.QCoreApplication.translate
        RevocationDialog.setWindowTitle(_translate("RevocationDialog", "Revoke an identity"))
        self.label.setText(_translate("RevocationDialog", "<h2>Select a revocation document</h1>"))
        self.button_load.setText(_translate("RevocationDialog", "Load from file"))
        self.groupBox.setTitle(_translate("RevocationDialog", "Revocation document"))
        self.label_2.setText(_translate("RevocationDialog", "<html><head/><body><p><span style=\" font-size:x-large; font-weight:600;\">Select publication destination</span></p></body></html>"))
        self.radio_currency.setText(_translate("RevocationDialog", "To a co&mmunity"))
        self.radio_address.setText(_translate("RevocationDialog", "&To an address"))
        self.checkbox_secured.setText(_translate("RevocationDialog", "SSL/TLS"))
        self.groupBox_2.setTitle(_translate("RevocationDialog", "Revocation information"))
        self.button_next.setText(_translate("RevocationDialog", "Next"))

