# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/builds/clients/python/sakia/src/sakia/gui/sub/certification/certification.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CertificationWidget(object):
    def setupUi(self, CertificationWidget):
        CertificationWidget.setObjectName("CertificationWidget")
        CertificationWidget.resize(724, 620)
        self.verticalLayout = QtWidgets.QVBoxLayout(CertificationWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(CertificationWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupbox_identity = QtWidgets.QGroupBox(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupbox_identity.sizePolicy().hasHeightForWidth())
        self.groupbox_identity.setSizePolicy(sizePolicy)
        self.groupbox_identity.setObjectName("groupbox_identity")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupbox_identity)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.combo_connections = QtWidgets.QComboBox(self.groupbox_identity)
        self.combo_connections.setObjectName("combo_connections")
        self.verticalLayout_2.addWidget(self.combo_connections)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupbox_identity)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_cert_stock = QtWidgets.QLabel(self.groupBox_3)
        self.label_cert_stock.setText("")
        self.label_cert_stock.setObjectName("label_cert_stock")
        self.verticalLayout_4.addWidget(self.label_cert_stock)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.verticalLayout_7.addWidget(self.groupbox_identity)
        self.groupbox_certified = QtWidgets.QGroupBox(self.page)
        self.groupbox_certified.setObjectName("groupbox_certified")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupbox_certified)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.identity_select_layout = QtWidgets.QHBoxLayout()
        self.identity_select_layout.setObjectName("identity_select_layout")
        self.button_import_identity = QtWidgets.QPushButton(self.groupbox_certified)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_import_identity.sizePolicy().hasHeightForWidth())
        self.button_import_identity.setSizePolicy(sizePolicy)
        self.button_import_identity.setObjectName("button_import_identity")
        self.identity_select_layout.addWidget(self.button_import_identity)
        self.verticalLayout_3.addLayout(self.identity_select_layout)
        self.verticalLayout_7.addWidget(self.groupbox_certified)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_process = QtWidgets.QPushButton(self.page)
        self.button_process.setObjectName("button_process")
        self.horizontalLayout.addWidget(self.button_process)
        self.button_cancel = QtWidgets.QPushButton(self.page)
        self.button_cancel.setObjectName("button_cancel")
        self.horizontalLayout.addWidget(self.button_cancel)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout_7.addWidget(self.frame)
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.groupBox = QtWidgets.QGroupBox(self.page_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.text_licence = QtWidgets.QTextEdit(self.groupBox)
        self.text_licence.setReadOnly(True)
        self.text_licence.setObjectName("text_licence")
        self.verticalLayout_5.addWidget(self.text_licence)
        self.label_confirm = QtWidgets.QLabel(self.groupBox)
        self.label_confirm.setObjectName("label_confirm")
        self.verticalLayout_5.addWidget(self.label_confirm)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.button_accept = QtWidgets.QPushButton(self.groupBox)
        self.button_accept.setObjectName("button_accept")
        self.horizontalLayout_2.addWidget(self.button_accept)
        self.button_cancel_licence = QtWidgets.QPushButton(self.groupBox)
        self.button_cancel_licence.setObjectName("button_cancel_licence")
        self.horizontalLayout_2.addWidget(self.button_cancel_licence)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_8.addWidget(self.groupBox)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.group_box_password = QtWidgets.QGroupBox(self.page_3)
        self.group_box_password.setObjectName("group_box_password")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.group_box_password)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.layout_password_input = QtWidgets.QVBoxLayout()
        self.layout_password_input.setObjectName("layout_password_input")
        self.verticalLayout_6.addLayout(self.layout_password_input)
        self.verticalLayout_9.addWidget(self.group_box_password)
        self.button_box = QtWidgets.QDialogButtonBox(self.page_3)
        self.button_box.setEnabled(True)
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.verticalLayout_9.addWidget(self.button_box)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.retranslateUi(CertificationWidget)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CertificationWidget)

    def retranslateUi(self, CertificationWidget):
        _translate = QtCore.QCoreApplication.translate
        CertificationWidget.setWindowTitle(_translate("CertificationWidget", "Form"))
        self.groupbox_identity.setTitle(_translate("CertificationWidget", "Select your identity"))
        self.groupBox_3.setTitle(_translate("CertificationWidget", "Certifications stock"))
        self.groupbox_certified.setTitle(_translate("CertificationWidget", "Certify user"))
        self.button_import_identity.setText(_translate("CertificationWidget", "Import identity document"))
        self.button_process.setText(_translate("CertificationWidget", "Process certification"))
        self.button_cancel.setText(_translate("CertificationWidget", "Cancel"))
        self.label.setText(_translate("CertificationWidget", "Step 1. Check the key and user / Step 2. Accept the money licence / Step 3. Sign to confirm certification"))
        self.groupBox.setTitle(_translate("CertificationWidget", "Licence"))
        self.label_confirm.setText(_translate("CertificationWidget", "By going throught the process of creating a wallet, you accept the license above."))
        self.button_accept.setText(_translate("CertificationWidget", "I accept the above licence"))
        self.button_cancel_licence.setText(_translate("CertificationWidget", "Cancel"))
        self.group_box_password.setTitle(_translate("CertificationWidget", "Secret Key / Password"))

