
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-14T12:31:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6f3cdd4f95eb7a3ca61a9eb03be599abdc785586",
 "version": "1.14.5.post.dev11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
