
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-13T14:52:50-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "d4ad74a819eff585b0553b9479dd853e75089489",
 "version": "0.14.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
