# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for
# license information.
#
# Code generated by Microsoft (R) AutoRest Code Generator 2.3.33.0
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class LocalRunGetNextTaskBatchInput(Model):
    """LocalRunGetNextTaskBatchInput.

    :param input_df:
    :type input_df: ~_restclient.models.MiroProxyInputDto
    :param parent_run_dto:
    :type parent_run_dto: ~_restclient.models.RunDto
    :param max_batch_size:
    :type max_batch_size: int
    :param version:
    :type version: int
    """

    _attribute_map = {
        'input_df': {'key': 'input_df', 'type': 'MiroProxyInputDto'},
        'parent_run_dto': {'key': 'parent_run_dto', 'type': 'RunDto'},
        'max_batch_size': {'key': 'max_batch_size', 'type': 'int'},
        'version': {'key': 'version', 'type': 'int'},
    }

    def __init__(self, input_df=None, parent_run_dto=None, max_batch_size=None, version=None):
        super(LocalRunGetNextTaskBatchInput, self).__init__()
        self.input_df = input_df
        self.parent_run_dto = parent_run_dto
        self.max_batch_size = max_batch_size
        self.version = version
