# Generated by Django 3.0.8 on 2020-07-12 12:43

import django.contrib.postgres.fields.jsonb
import django.contrib.sites.managers
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_alter_domain_unique"),
        ("alsijil", "0002_excuse_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtraMark",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extended_data",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        default=dict, editable=False
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Short name"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                (
                    "site",
                    models.ForeignKey(
                        default=1,
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sites.Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extra mark",
                "verbose_name_plural": "Extra marks",
                "ordering": ["short_name"],
            },
            managers=[("objects", django.contrib.sites.managers.CurrentSiteManager()),],
        ),
        migrations.AddField(
            model_name="personalnote",
            name="extra_marks",
            field=models.ManyToManyField(
                blank=True,
                to="alsijil.ExtraMark",
                verbose_name="Extra marks",
            ),
        ),
    ]
