# Generated by Django 3.0.8 on 2020-07-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alsijil", "0005_groups_of_person"),
    ]

    operations = [
        migrations.DeleteModel(name="PersonalNoteFilter",),
    ]
