# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/builds/clients/python/sakia/src/sakia/gui/navigation/txhistory/txhistory.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TxHistoryWidget(object):
    def setupUi(self, TxHistoryWidget):
        TxHistoryWidget.setObjectName("TxHistoryWidget")
        TxHistoryWidget.resize(656, 635)
        self.verticalLayout = QtWidgets.QVBoxLayout(TxHistoryWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupbox_balance = QtWidgets.QGroupBox(TxHistoryWidget)
        self.groupbox_balance.setObjectName("groupbox_balance")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupbox_balance)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label_balance = QtWidgets.QLabel(self.groupbox_balance)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_balance.setFont(font)
        self.label_balance.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_balance.setObjectName("label_balance")
        self.horizontalLayout.addWidget(self.label_balance)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.button_send = QtWidgets.QPushButton(self.groupbox_balance)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/payment_icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_send.setIcon(icon)
        self.button_send.setIconSize(QtCore.QSize(24, 16))
        self.button_send.setObjectName("button_send")
        self.horizontalLayout.addWidget(self.button_send)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.busy_balance = Busy(self.groupbox_balance)
        self.busy_balance.setObjectName("busy_balance")
        self.verticalLayout_4.addWidget(self.busy_balance)
        self.verticalLayout.addWidget(self.groupbox_balance)
        self.stacked_widget = QtWidgets.QStackedWidget(TxHistoryWidget)
        self.stacked_widget.setObjectName("stacked_widget")
        self.page_history = QtWidgets.QWidget()
        self.page_history.setObjectName("page_history")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.page_history)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(-1, 5, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.date_from = QtWidgets.QDateTimeEdit(self.page_history)
        self.date_from.setCalendarPopup(True)
        self.date_from.setObjectName("date_from")
        self.horizontalLayout_2.addWidget(self.date_from)
        self.date_to = QtWidgets.QDateTimeEdit(self.page_history)
        self.date_to.setCalendarPopup(True)
        self.date_to.setObjectName("date_to")
        self.horizontalLayout_2.addWidget(self.date_to)
        self.button_refresh = QtWidgets.QPushButton(self.page_history)
        self.button_refresh.setMaximumSize(QtCore.QSize(30, 30))
        self.button_refresh.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/refresh_icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_refresh.setIcon(icon1)
        self.button_refresh.setIconSize(QtCore.QSize(16, 16))
        self.button_refresh.setObjectName("button_refresh")
        self.horizontalLayout_2.addWidget(self.button_refresh)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.table_history = QtWidgets.QTableView(self.page_history)
        self.table_history.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.table_history.setAlternatingRowColors(True)
        self.table_history.setShowGrid(True)
        self.table_history.setObjectName("table_history")
        self.table_history.horizontalHeader().setSortIndicatorShown(True)
        self.table_history.horizontalHeader().setStretchLastSection(True)
        self.table_history.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.table_history)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.page_history)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.spin_page = QtWidgets.QSpinBox(self.page_history)
        self.spin_page.setObjectName("spin_page")
        self.horizontalLayout_3.addWidget(self.spin_page)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.stacked_widget.addWidget(self.page_history)
        self.verticalLayout.addWidget(self.stacked_widget)

        self.retranslateUi(TxHistoryWidget)
        self.stacked_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TxHistoryWidget)

    def retranslateUi(self, TxHistoryWidget):
        _translate = QtCore.QCoreApplication.translate
        TxHistoryWidget.setWindowTitle(_translate("TxHistoryWidget", "Form"))
        self.groupbox_balance.setTitle(_translate("TxHistoryWidget", "Balance"))
        self.label_balance.setText(_translate("TxHistoryWidget", "loading..."))
        self.button_send.setText(_translate("TxHistoryWidget", "Send money"))
        self.date_from.setDisplayFormat(_translate("TxHistoryWidget", "dd/MM/yyyy"))
        self.date_to.setDisplayFormat(_translate("TxHistoryWidget", "dd/MM/yyyy"))
        self.label.setText(_translate("TxHistoryWidget", "<html><head/><body><p><span style=\" color:#0000ff;\">■</span><span style=\" font-style:italic;\">to send </span><span style=\" color:#ffb000;\">■</span><span style=\" font-style:italic;\">pending </span><span style=\" color:#808080;\">■</span><span style=\" font-style:italic;\">refused </span><span style=\" color:#000000;\">■</span><span style=\" font-style:italic;\">not confirmed </span><span style=\" color:#000000;\">■</span>validated <span style=\" color:#000000;\">■ </span><span style=\" text-decoration: underline;\">to unlock</span></p></body></html>"))

from sakia.gui.widgets import Busy
import sakia.icons_rc
