#!/usr/bin/env python3
# -*- coding: utf-8 -*-


import pandas as pd
from collections import OrderedDict

dc_yaliwc_dict_big2a_agency = OrderedDict()

dc_yaliwc_dict_big2a_agency[ "able"           ] = 1
dc_yaliwc_dict_big2a_agency[ "accomplish*"    ] = 1
dc_yaliwc_dict_big2a_agency[ "accurac*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "accurate*"      ] = 1
dc_yaliwc_dict_big2a_agency[ "achiev*"        ] = 1
dc_yaliwc_dict_big2a_agency[ "acquir*"        ] = 1
dc_yaliwc_dict_big2a_agency[ "actualiz*"      ] = 1
dc_yaliwc_dict_big2a_agency[ "adaptab*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "adept*"         ] = 1
dc_yaliwc_dict_big2a_agency[ "ambition*"      ] = 1
dc_yaliwc_dict_big2a_agency[ "ambitious*"     ] = 1
dc_yaliwc_dict_big2a_agency[ "aptitude*"      ] = 1
dc_yaliwc_dict_big2a_agency[ "aptly"          ] = 1
dc_yaliwc_dict_big2a_agency[ "aptness"        ] = 1
dc_yaliwc_dict_big2a_agency[ "aspiration*"    ] = 1
dc_yaliwc_dict_big2a_agency[ "aspire*"        ] = 1
dc_yaliwc_dict_big2a_agency[ "aspiring"       ] = 1
dc_yaliwc_dict_big2a_agency[ "assert*"        ] = 1
dc_yaliwc_dict_big2a_agency[ "attain*"        ] = 1
dc_yaliwc_dict_big2a_agency[ "authoritative*" ] = 1
dc_yaliwc_dict_big2a_agency[ "autonomous*"    ] = 1
dc_yaliwc_dict_big2a_agency[ "autonomy"       ] = 1
dc_yaliwc_dict_big2a_agency[ "capab*"         ] = 1
dc_yaliwc_dict_big2a_agency[ "careful*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "choice"         ] = 1
dc_yaliwc_dict_big2a_agency[ "choices"        ] = 1
dc_yaliwc_dict_big2a_agency[ "clever*"        ] = 1
dc_yaliwc_dict_big2a_agency[ "compet*"        ] = 1
dc_yaliwc_dict_big2a_agency[ "completion"     ] = 1
dc_yaliwc_dict_big2a_agency[ "confident"      ] = 1
dc_yaliwc_dict_big2a_agency[ "confidently"    ] = 1
dc_yaliwc_dict_big2a_agency[ "conquer*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "conscientious*" ] = 1
dc_yaliwc_dict_big2a_agency[ "contemplat*"    ] = 1
dc_yaliwc_dict_big2a_agency[ "contend*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "contest*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "decid*"         ] = 1
dc_yaliwc_dict_big2a_agency[ "decision*"      ] = 1
dc_yaliwc_dict_big2a_agency[ "decisive*"      ] = 1
dc_yaliwc_dict_big2a_agency[ "defeat*"        ] = 1
dc_yaliwc_dict_big2a_agency[ "deliberat*"     ] = 1
dc_yaliwc_dict_big2a_agency[ "dependable"     ] = 1
dc_yaliwc_dict_big2a_agency[ "determin*"      ] = 1
dc_yaliwc_dict_big2a_agency[ "difficult*"     ] = 1
dc_yaliwc_dict_big2a_agency[ "do"             ] = 1
dc_yaliwc_dict_big2a_agency[ "doable"         ] = 1
dc_yaliwc_dict_big2a_agency[ "doing"          ] = 1
dc_yaliwc_dict_big2a_agency[ "eager*"         ] = 1
dc_yaliwc_dict_big2a_agency[ "earn"           ] = 1
dc_yaliwc_dict_big2a_agency[ "earned"         ] = 1
dc_yaliwc_dict_big2a_agency[ "earning"        ] = 1
dc_yaliwc_dict_big2a_agency[ "earns"          ] = 1
dc_yaliwc_dict_big2a_agency[ "easiness"       ] = 1
dc_yaliwc_dict_big2a_agency[ "easy"           ] = 1
dc_yaliwc_dict_big2a_agency[ "effective*"     ] = 1
dc_yaliwc_dict_big2a_agency[ "efficien*"      ] = 1
dc_yaliwc_dict_big2a_agency[ "effort*"        ] = 1
dc_yaliwc_dict_big2a_agency[ "empowered"      ] = 1
dc_yaliwc_dict_big2a_agency[ "enact*"         ] = 1
dc_yaliwc_dict_big2a_agency[ "endeavor*"      ] = 1
dc_yaliwc_dict_big2a_agency[ "establish"      ] = 1
dc_yaliwc_dict_big2a_agency[ "established"    ] = 1
dc_yaliwc_dict_big2a_agency[ "establishes"    ] = 1
dc_yaliwc_dict_big2a_agency[ "establishing"   ] = 1
dc_yaliwc_dict_big2a_agency[ "exact*"         ] = 1
dc_yaliwc_dict_big2a_agency[ "expert*"        ] = 1
dc_yaliwc_dict_big2a_agency[ "fail*"          ] = 1
dc_yaliwc_dict_big2a_agency[ "fluen*"         ] = 1
dc_yaliwc_dict_big2a_agency[ "freedom*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "freely"         ] = 1
dc_yaliwc_dict_big2a_agency[ "goal"           ] = 1
dc_yaliwc_dict_big2a_agency[ "goal-oriented"  ] = 1
dc_yaliwc_dict_big2a_agency[ "goals"          ] = 1
dc_yaliwc_dict_big2a_agency[ "importan*"      ] = 1
dc_yaliwc_dict_big2a_agency[ "independ*"      ] = 1
dc_yaliwc_dict_big2a_agency[ "individualist"  ] = 1
dc_yaliwc_dict_big2a_agency[ "insight*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "intent*"        ] = 1
dc_yaliwc_dict_big2a_agency[ "intuition"      ] = 1
dc_yaliwc_dict_big2a_agency[ "intuitive*"     ] = 1
dc_yaliwc_dict_big2a_agency[ "keen*"          ] = 1
dc_yaliwc_dict_big2a_agency[ "know*"          ] = 1
dc_yaliwc_dict_big2a_agency[ "liberties"      ] = 1
dc_yaliwc_dict_big2a_agency[ "liberty"        ] = 1
dc_yaliwc_dict_big2a_agency[ "logic*"         ] = 1
dc_yaliwc_dict_big2a_agency[ "loner*"         ] = 1
dc_yaliwc_dict_big2a_agency[ "made"           ] = 1
dc_yaliwc_dict_big2a_agency[ "make"           ] = 1
dc_yaliwc_dict_big2a_agency[ "makes"          ] = 1
dc_yaliwc_dict_big2a_agency[ "making"         ] = 1
dc_yaliwc_dict_big2a_agency[ "mastered"       ] = 1
dc_yaliwc_dict_big2a_agency[ "masterful*"     ] = 1
dc_yaliwc_dict_big2a_agency[ "mastering"      ] = 1
dc_yaliwc_dict_big2a_agency[ "mastery"        ] = 1
dc_yaliwc_dict_big2a_agency[ "motivat*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "need"           ] = 1
dc_yaliwc_dict_big2a_agency[ "needed"         ] = 1
dc_yaliwc_dict_big2a_agency[ "needing"        ] = 1
dc_yaliwc_dict_big2a_agency[ "needs"          ] = 1
dc_yaliwc_dict_big2a_agency[ "objectiv*"      ] = 1
dc_yaliwc_dict_big2a_agency[ "obtain*"        ] = 1
dc_yaliwc_dict_big2a_agency[ "opportun*"      ] = 1
dc_yaliwc_dict_big2a_agency[ "overcame"       ] = 1
dc_yaliwc_dict_big2a_agency[ "overcome"       ] = 1
dc_yaliwc_dict_big2a_agency[ "overcomes"      ] = 1
dc_yaliwc_dict_big2a_agency[ "overcoming"     ] = 1
dc_yaliwc_dict_big2a_agency[ "persever*"      ] = 1
dc_yaliwc_dict_big2a_agency[ "persist*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "persistent"     ] = 1
dc_yaliwc_dict_big2a_agency[ "pioneer*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "practic*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "pragmat*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "prevail*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "pride"          ] = 1
dc_yaliwc_dict_big2a_agency[ "prideful*"      ] = 1
dc_yaliwc_dict_big2a_agency[ "priorit*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "proactive*"     ] = 1
dc_yaliwc_dict_big2a_agency[ "productive*"    ] = 1
dc_yaliwc_dict_big2a_agency[ "productivity"   ] = 1
dc_yaliwc_dict_big2a_agency[ "proficien*"     ] = 1
dc_yaliwc_dict_big2a_agency[ "prosper*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "proud*"         ] = 1
dc_yaliwc_dict_big2a_agency[ "purpose*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "pursu*"         ] = 1
dc_yaliwc_dict_big2a_agency[ "rational*"      ] = 1
dc_yaliwc_dict_big2a_agency[ "realiz*"        ] = 1
dc_yaliwc_dict_big2a_agency[ "rebel*"         ] = 1
dc_yaliwc_dict_big2a_agency[ "recog*"         ] = 1
dc_yaliwc_dict_big2a_agency[ "reliab*"        ] = 1
dc_yaliwc_dict_big2a_agency[ "reputation*"    ] = 1
dc_yaliwc_dict_big2a_agency[ "resilien*"      ] = 1
dc_yaliwc_dict_big2a_agency[ "resolute*"      ] = 1
dc_yaliwc_dict_big2a_agency[ "resolution"     ] = 1
dc_yaliwc_dict_big2a_agency[ "resolv*"        ] = 1
dc_yaliwc_dict_big2a_agency[ "responsib*"     ] = 1
dc_yaliwc_dict_big2a_agency[ "reward*"        ] = 1
dc_yaliwc_dict_big2a_agency[ "risk*"          ] = 1
dc_yaliwc_dict_big2a_agency[ "savv*"          ] = 1
dc_yaliwc_dict_big2a_agency[ "score"          ] = 1
dc_yaliwc_dict_big2a_agency[ "scored"         ] = 1
dc_yaliwc_dict_big2a_agency[ "scores"         ] = 1
dc_yaliwc_dict_big2a_agency[ "scoring"        ] = 1
dc_yaliwc_dict_big2a_agency[ "self"           ] = 1
dc_yaliwc_dict_big2a_agency[ "self-*"         ] = 1
dc_yaliwc_dict_big2a_agency[ "should*"        ] = 1
dc_yaliwc_dict_big2a_agency[ "significant*"   ] = 1
dc_yaliwc_dict_big2a_agency[ "skill"          ] = 1
dc_yaliwc_dict_big2a_agency[ "skilled"        ] = 1
dc_yaliwc_dict_big2a_agency[ "skillful*"      ] = 1
dc_yaliwc_dict_big2a_agency[ "skills*"        ] = 1
dc_yaliwc_dict_big2a_agency[ "smart"          ] = 1
dc_yaliwc_dict_big2a_agency[ "smartly"        ] = 1
dc_yaliwc_dict_big2a_agency[ "steadfast*"     ] = 1
dc_yaliwc_dict_big2a_agency[ "strive*"        ] = 1
dc_yaliwc_dict_big2a_agency[ "striving*"      ] = 1
dc_yaliwc_dict_big2a_agency[ "struggl*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "stubborn*"      ] = 1
dc_yaliwc_dict_big2a_agency[ "succeed*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "success*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "sure"           ] = 1
dc_yaliwc_dict_big2a_agency[ "take"           ] = 1
dc_yaliwc_dict_big2a_agency[ "takes"          ] = 1
dc_yaliwc_dict_big2a_agency[ "taking"         ] = 1
dc_yaliwc_dict_big2a_agency[ "tenac*"         ] = 1
dc_yaliwc_dict_big2a_agency[ "think*"         ] = 1
dc_yaliwc_dict_big2a_agency[ "thought"        ] = 1
dc_yaliwc_dict_big2a_agency[ "took"           ] = 1
dc_yaliwc_dict_big2a_agency[ "tried"          ] = 1
dc_yaliwc_dict_big2a_agency[ "tries"          ] = 1
dc_yaliwc_dict_big2a_agency[ "triumph*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "trying"         ] = 1
dc_yaliwc_dict_big2a_agency[ "unaided"        ] = 1
dc_yaliwc_dict_big2a_agency[ "unyielding*"    ] = 1
dc_yaliwc_dict_big2a_agency[ "vanquish*"      ] = 1
dc_yaliwc_dict_big2a_agency[ "victor*"        ] = 1
dc_yaliwc_dict_big2a_agency[ "will"           ] = 1
dc_yaliwc_dict_big2a_agency[ "willing*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "willpower"      ] = 1
dc_yaliwc_dict_big2a_agency[ "win"            ] = 1
dc_yaliwc_dict_big2a_agency[ "winner*"        ] = 1
dc_yaliwc_dict_big2a_agency[ "winning*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "wins"           ] = 1
dc_yaliwc_dict_big2a_agency[ "wit"            ] = 1
dc_yaliwc_dict_big2a_agency[ "wits"           ] = 1
dc_yaliwc_dict_big2a_agency[ "witting*"       ] = 1
dc_yaliwc_dict_big2a_agency[ "won"            ] = 1
dc_yaliwc_dict_big2a_agency[ "won't"          ] = 1
dc_yaliwc_dict_big2a_agency[ "you"            ] = 1
dc_yaliwc_dict_big2a_agency[ "you'*"          ] = 1
dc_yaliwc_dict_big2a_agency[ "your"           ] = 1
dc_yaliwc_dict_big2a_agency[ "yours"          ] = 1
dc_yaliwc_dict_big2a_agency[ "yourself"       ] = 1

df_yaliwc_dict_big2a_agency = pd.DataFrame.from_dict(
    data    = dc_yaliwc_dict_big2a_agency,
    orient  = 'index',
    columns = ['weights',],
)

df_yaliwc_dict_big2a_agency["items"] = df_yaliwc_dict_big2a_agency.index
df_yaliwc_dict_big2a_agency = df_yaliwc_dict_big2a_agency[["items","weights",]]

def save__yaliwc_dict_big2a_agency( fn="yaliwc_dict_big2a_agency.csv", ):
    df_yaliwc_dict_big2a_agency.to_csv(fn,index=False,)


if __name__ == "__main__":
    save__yaliwc_dict_big2a_agency()
