#!/usr/bin/env python3
# -*- coding: utf-8 -*-


import pandas as pd
from collections import OrderedDict

dc_yaliwc_dict_big2a_commun = OrderedDict()

dc_yaliwc_dict_big2a_commun[ "accept*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "accommodat*"    ] = 1
dc_yaliwc_dict_big2a_commun[ "accompan*"      ] = 1
dc_yaliwc_dict_big2a_commun[ "accord"         ] = 1
dc_yaliwc_dict_big2a_commun[ "affab*"         ] = 1
dc_yaliwc_dict_big2a_commun[ "affection*"     ] = 1
dc_yaliwc_dict_big2a_commun[ "affiliat*"      ] = 1
dc_yaliwc_dict_big2a_commun[ "affinity"       ] = 1
dc_yaliwc_dict_big2a_commun[ "agree*"         ] = 1
dc_yaliwc_dict_big2a_commun[ "aid"            ] = 1
dc_yaliwc_dict_big2a_commun[ "aided"          ] = 1
dc_yaliwc_dict_big2a_commun[ "aiding"         ] = 1
dc_yaliwc_dict_big2a_commun[ "allegian*"      ] = 1
dc_yaliwc_dict_big2a_commun[ "alliance*"      ] = 1
dc_yaliwc_dict_big2a_commun[ "allies"         ] = 1
dc_yaliwc_dict_big2a_commun[ "ally"           ] = 1
dc_yaliwc_dict_big2a_commun[ "altruis*"       ] = 1
dc_yaliwc_dict_big2a_commun[ "amenab*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "amiab*"         ] = 1
dc_yaliwc_dict_big2a_commun[ "amicab*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "amigo*"         ] = 1
dc_yaliwc_dict_big2a_commun[ "apolog*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "appreciat*"     ] = 1
dc_yaliwc_dict_big2a_commun[ "assist*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "benevolen*"     ] = 1
dc_yaliwc_dict_big2a_commun[ "buddies"        ] = 1
dc_yaliwc_dict_big2a_commun[ "buddy"          ] = 1
dc_yaliwc_dict_big2a_commun[ "care"           ] = 1
dc_yaliwc_dict_big2a_commun[ "cared"          ] = 1
dc_yaliwc_dict_big2a_commun[ "cares"          ] = 1
dc_yaliwc_dict_big2a_commun[ "caring*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "ceremon*"       ] = 1
dc_yaliwc_dict_big2a_commun[ "charit*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "chat"           ] = 1
dc_yaliwc_dict_big2a_commun[ "chats"          ] = 1
dc_yaliwc_dict_big2a_commun[ "chatted"        ] = 1
dc_yaliwc_dict_big2a_commun[ "chatting"       ] = 1
dc_yaliwc_dict_big2a_commun[ "civic"          ] = 1
dc_yaliwc_dict_big2a_commun[ "civil*"         ] = 1
dc_yaliwc_dict_big2a_commun[ "closeness"      ] = 1
dc_yaliwc_dict_big2a_commun[ "collab*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "colleague*"     ] = 1
dc_yaliwc_dict_big2a_commun[ "collective*"    ] = 1
dc_yaliwc_dict_big2a_commun[ "common good"    ] = 1
dc_yaliwc_dict_big2a_commun[ "common ground*" ] = 1
dc_yaliwc_dict_big2a_commun[ "commun*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "companion*"     ] = 1
dc_yaliwc_dict_big2a_commun[ "compassion*"    ] = 1
dc_yaliwc_dict_big2a_commun[ "compromis*"     ] = 1
dc_yaliwc_dict_big2a_commun[ "concert*"       ] = 1
dc_yaliwc_dict_big2a_commun[ "confer*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "congrat*"       ] = 1
dc_yaliwc_dict_big2a_commun[ "consen*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "considerate*"   ] = 1
dc_yaliwc_dict_big2a_commun[ "contribut*"     ] = 1
dc_yaliwc_dict_big2a_commun[ "conversat*"     ] = 1
dc_yaliwc_dict_big2a_commun[ "converse"       ] = 1
dc_yaliwc_dict_big2a_commun[ "conversed"      ] = 1
dc_yaliwc_dict_big2a_commun[ "converses"      ] = 1
dc_yaliwc_dict_big2a_commun[ "conversing"     ] = 1
dc_yaliwc_dict_big2a_commun[ "cooperat*"      ] = 1
dc_yaliwc_dict_big2a_commun[ "counsel*"       ] = 1
dc_yaliwc_dict_big2a_commun[ "courteous*"     ] = 1
dc_yaliwc_dict_big2a_commun[ "crew"           ] = 1
dc_yaliwc_dict_big2a_commun[ "democr*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "dialogue*"      ] = 1
dc_yaliwc_dict_big2a_commun[ "discuss*"       ] = 1
dc_yaliwc_dict_big2a_commun[ "educat*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "empath*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "equitab*"       ] = 1
dc_yaliwc_dict_big2a_commun[ "familial"       ] = 1
dc_yaliwc_dict_big2a_commun[ "families"       ] = 1
dc_yaliwc_dict_big2a_commun[ "family"         ] = 1
dc_yaliwc_dict_big2a_commun[ "familys'"       ] = 1
dc_yaliwc_dict_big2a_commun[ "family's"       ] = 1
dc_yaliwc_dict_big2a_commun[ "fellow*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "festiv*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "forgave"        ] = 1
dc_yaliwc_dict_big2a_commun[ "forgiv*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "frat*"          ] = 1
dc_yaliwc_dict_big2a_commun[ "friend*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "generos*"       ] = 1
dc_yaliwc_dict_big2a_commun[ "generous*"      ] = 1
dc_yaliwc_dict_big2a_commun[ "grateful*"      ] = 1
dc_yaliwc_dict_big2a_commun[ "gregarious*"    ] = 1
dc_yaliwc_dict_big2a_commun[ "group*"         ] = 1
dc_yaliwc_dict_big2a_commun[ "guidanc*"       ] = 1
dc_yaliwc_dict_big2a_commun[ "harmon*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "help*"          ] = 1
dc_yaliwc_dict_big2a_commun[ "honest*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "hospitab*"      ] = 1
dc_yaliwc_dict_big2a_commun[ "hospitality"    ] = 1
dc_yaliwc_dict_big2a_commun[ "human*"         ] = 1
dc_yaliwc_dict_big2a_commun[ "impartial*"     ] = 1
dc_yaliwc_dict_big2a_commun[ "interpersonal*" ] = 1
dc_yaliwc_dict_big2a_commun[ "intima*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "justice"        ] = 1
dc_yaliwc_dict_big2a_commun[ "justly"         ] = 1
dc_yaliwc_dict_big2a_commun[ "kin"            ] = 1
dc_yaliwc_dict_big2a_commun[ "kindly"         ] = 1
dc_yaliwc_dict_big2a_commun[ "kindness"       ] = 1
dc_yaliwc_dict_big2a_commun[ "kinship"        ] = 1
dc_yaliwc_dict_big2a_commun[ "law"            ] = 1
dc_yaliwc_dict_big2a_commun[ "lawful*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "laws"           ] = 1
dc_yaliwc_dict_big2a_commun[ "learn*"         ] = 1
dc_yaliwc_dict_big2a_commun[ "love*"          ] = 1
dc_yaliwc_dict_big2a_commun[ "loving*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "loyal*"         ] = 1
dc_yaliwc_dict_big2a_commun[ "magnanimous*"   ] = 1
dc_yaliwc_dict_big2a_commun[ "marriag*"       ] = 1
dc_yaliwc_dict_big2a_commun[ "matrimon*"      ] = 1
dc_yaliwc_dict_big2a_commun[ "member*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "middle ground"  ] = 1
dc_yaliwc_dict_big2a_commun[ "mingl*"         ] = 1
dc_yaliwc_dict_big2a_commun[ "mutual*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "negotiat*"      ] = 1
dc_yaliwc_dict_big2a_commun[ "neighbor*"      ] = 1
dc_yaliwc_dict_big2a_commun[ "nurtur*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "offer*"         ] = 1
dc_yaliwc_dict_big2a_commun[ "oneness"        ] = 1
dc_yaliwc_dict_big2a_commun[ "open-mind*"     ] = 1
dc_yaliwc_dict_big2a_commun[ "our"            ] = 1
dc_yaliwc_dict_big2a_commun[ "ours"           ] = 1
dc_yaliwc_dict_big2a_commun[ "pal"            ] = 1
dc_yaliwc_dict_big2a_commun[ "pals"           ] = 1
dc_yaliwc_dict_big2a_commun[ "participat*"    ] = 1
dc_yaliwc_dict_big2a_commun[ "partied"        ] = 1
dc_yaliwc_dict_big2a_commun[ "parties"        ] = 1
dc_yaliwc_dict_big2a_commun[ "partner*"       ] = 1
dc_yaliwc_dict_big2a_commun[ "party*"         ] = 1
dc_yaliwc_dict_big2a_commun[ "philanth*"      ] = 1
dc_yaliwc_dict_big2a_commun[ "pluralis*"      ] = 1
dc_yaliwc_dict_big2a_commun[ "polite*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "public"         ] = 1
dc_yaliwc_dict_big2a_commun[ "publicly"       ] = 1
dc_yaliwc_dict_big2a_commun[ "recipr*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "recommend*"     ] = 1
dc_yaliwc_dict_big2a_commun[ "reconcil*"      ] = 1
dc_yaliwc_dict_big2a_commun[ "relationship*"  ] = 1
dc_yaliwc_dict_big2a_commun[ "request*"       ] = 1
dc_yaliwc_dict_big2a_commun[ "respect*"       ] = 1
dc_yaliwc_dict_big2a_commun[ "ritual*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "roommate*"      ] = 1
dc_yaliwc_dict_big2a_commun[ "sacrific*"      ] = 1
dc_yaliwc_dict_big2a_commun[ "selfless*"      ] = 1
dc_yaliwc_dict_big2a_commun[ "servic*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "share"          ] = 1
dc_yaliwc_dict_big2a_commun[ "shared"         ] = 1
dc_yaliwc_dict_big2a_commun[ "shares"         ] = 1
dc_yaliwc_dict_big2a_commun[ "sharing"        ] = 1
dc_yaliwc_dict_big2a_commun[ "sincer*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "socia*"         ] = 1
dc_yaliwc_dict_big2a_commun[ "societ*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "solidarity"     ] = 1
dc_yaliwc_dict_big2a_commun[ "soror*"         ] = 1
dc_yaliwc_dict_big2a_commun[ "squad*"         ] = 1
dc_yaliwc_dict_big2a_commun[ "suggest*"       ] = 1
dc_yaliwc_dict_big2a_commun[ "support*"       ] = 1
dc_yaliwc_dict_big2a_commun[ "sympath*"       ] = 1
dc_yaliwc_dict_big2a_commun[ "talk*"          ] = 1
dc_yaliwc_dict_big2a_commun[ "taught"         ] = 1
dc_yaliwc_dict_big2a_commun[ "teach*"         ] = 1
dc_yaliwc_dict_big2a_commun[ "team*"          ] = 1
dc_yaliwc_dict_big2a_commun[ "thank*"         ] = 1
dc_yaliwc_dict_big2a_commun[ "together*"      ] = 1
dc_yaliwc_dict_big2a_commun[ "tradition*"     ] = 1
dc_yaliwc_dict_big2a_commun[ "treatise*"      ] = 1
dc_yaliwc_dict_big2a_commun[ "treaty"         ] = 1
dc_yaliwc_dict_big2a_commun[ "tribe*"         ] = 1
dc_yaliwc_dict_big2a_commun[ "trust*"         ] = 1
dc_yaliwc_dict_big2a_commun[ "truth*"         ] = 1
dc_yaliwc_dict_big2a_commun[ "unanim*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "unif*"          ] = 1
dc_yaliwc_dict_big2a_commun[ "unite*"         ] = 1
dc_yaliwc_dict_big2a_commun[ "uniting"        ] = 1
dc_yaliwc_dict_big2a_commun[ "unity"          ] = 1
dc_yaliwc_dict_big2a_commun[ "unselfish*"     ] = 1
dc_yaliwc_dict_big2a_commun[ "us"             ] = 1
dc_yaliwc_dict_big2a_commun[ "volunt*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "we"             ] = 1
dc_yaliwc_dict_big2a_commun[ "welcom*"        ] = 1
dc_yaliwc_dict_big2a_commun[ "welfare"        ] = 1
dc_yaliwc_dict_big2a_commun[ "inclusiv*"      ] = 1


df_yaliwc_dict_big2a_commun = pd.DataFrame.from_dict(
    data    = dc_yaliwc_dict_big2a_commun,
    orient  = 'index',
    columns = ['weights',],
)

df_yaliwc_dict_big2a_commun["items"] = df_yaliwc_dict_big2a_commun.index
df_yaliwc_dict_big2a_commun = df_yaliwc_dict_big2a_commun[["items","weights",]]

def save__yaliwc_dict_big2a_commun( fn="yaliwc_dict_big2a_commun.csv", ):
    df_yaliwc_dict_big2a_commun.to_csv(fn,index=False,)


if __name__ == "__main__":
    save__yaliwc_dict_big2a_commun()
