
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-12T15:48:55+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b7cecdf8daa4de6e527a0f32fa4451b985c31f73",
 "version": "0.6.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
