# Generated by Django 2.2.17 on 2021-01-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoldp_invoice', '0004_auto_20201210_0828'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'control')},
        ),
        migrations.AlterModelOptions(
            name='customerinvoice',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'control')},
        ),
        migrations.AlterModelOptions(
            name='freelanceinvoice',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'control')},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'control')},
        ),
    ]
