
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-13T11:55:48-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0626db4166ef7b6d45523b10d38da87649ed17bd",
 "version": "0.13"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
