
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-01-10T14:07:09-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "b51cfb86c39bda190e0ac876435fa8f048b7ddd5",
 "version": "3.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
