# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from opera.api.openapi.models.base_model_ import Model
from opera.api.openapi import util


class PackagingFormat(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    ZIP = "zip"
    TAR = "tar"
    def __init__(self):  # noqa: E501
        """PackagingFormat - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'PackagingFormat':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PackagingFormat of this PackagingFormat.  # noqa: E501
        :rtype: PackagingFormat
        """
        return util.deserialize_model(dikt, cls)
